export default {
	labels:{
		// formats
		"common": "Všeobecné",
		"currency": "Měna",
		"number": "Numerické",
		"percent": "Procento",
		"date": "Datum",
		"string": "Text",
		"custom-format": "Nestandardní",
		"decimal-places":"Desetinná místa",
		"separator":"Oddělovač skupin",
		"negative":"Záporné číslo",
		"date-format":"Datový formát",
		"format-docs":"Jak vytvořit formát",
		// titles
		"undo-redo": "Zpět/Opakovat",
		"font": "Písmo",
		"text": "Text",
		"cell": "Buňka",
		"align": "Zarovnání",
		"format": "Číslo",
		"column": "Sloupec",
		"borders": " Ohraničení",
		"px": "px",
		"apply": "Aplikovat",
		// popups and dialogs
		"cancel": "Zrušení",
		"save": "Uložit",
		// multisheets
		"sheet": "Prostěradlo",
		// conditions
		"conditional-format": "Podmíněné formátování",
		"condition": "Předpoklad",
		"conditional-style": "Styl",
		"conditional-operator": "Pravidlo",
		"conditional-between":"Mezi",
		"conditional-not-equal":"Nerovná se",
		// ranges
		"range": "Rozsah",
		"range-title": "Pojmenované rozsahy",
		"range-name": "Název",
		"range-cells": "Rozsah",
		"range-scope": "Rozsah",
		"range-global": "Book",
		// images
		"image-or": "nebo",
		"image-title": "Přidat obrázek",
		"image-upload": "Vyberte soubor k nahrání",
		"image-url": "URL (e.g. http://*)",
		// sparklines
		"sparkline-title": "Add sparkline",
		"sparkline-type": "Typ",
		"sparkline-range": "Rozsah",
		"sparkline-color": "Barva",
		"sparkline-positive": "Positive",
		"sparkline-negative": "Negative",
		// custom format
		"format-title": "Nastavit formát",
		"format-pattern": "Format pattern",
		//dropdown
		"dropdown-empty": "Prázdné buňky",
		"dropdown-title": "Přidat rozbalovací nabídku",
		"dropdown-range": "Rozsah",
		// confirm
		"ok": "OK",
		// import/export
		"import-title": "Import",
		"import-not-support": "Litujeme, váš prohlížeč nepodporuje import",
		"export-title": "Exportovat",
		"export-name": "Název souboru xlsx",
		"export-all-sheets":"Exportovat všechny listy",
		// add link
		"link-title": "Přidat odkaz",
		"link-name": "Text",
		"link-url": "URL",
		//images
		"image": "Obraz",
		"add-image-cell":"Přidat do buňky",
		"add-image-top":"Add above cells",
		//charts
		"graph": "Graf",
		"add-sparkline":"Přidat do buňky",
		"add-chart":"Add above cells",
		//conditional format labels
		"display" : "Styl",
		"value" : "Hodnota",
		// confirm messages
		"range-remove-confirm": "Opravdu chcete rozsah trvale odstranit?",
		"sheet-remove-confirm": "Opravdu chcete list trvale odstranit?",
		"merge-cell-confirm":"Po sloučení zůstane pouze hodnota vlevo nahoře. Pokračovat?",
		"error-range": "Rozsah je nesprávný!",
		//print
		"print":"Tisk",
		"print-title":"Před tiskem ..",
		"print-settings":"Základní nastavení",
		"print-paper":"Velikost papíru",
		"print-layout":"Rozložení",
		"sheets":"Listy",
		"selection":"Vybrané buňky",
		"borderless":"Skrýt mřížku",
		"sheet-names":"Zobrazit názvy listů",
		"skip-rows":"Přeskočit prázdné řádky",
		"margin":"Skrýt okraje",
		"page-letter":"Dopis",
		"page-a4":"A4 (210x297mm)",
		"page-a3":"A3 (297x420mm)",
		"page-width":"Šířka stránky",
		"page-actual":"Aktuální velikost",
		"page-portrait":"Svislá orientace",
		"page-landscape":"Vodorovná orientace",
		//comment
		"comment":"Komentář",
		//resize
		"width":"Šířka",
		"height":"Výška",
		"fit-content": "Přizpůsobit obsahu",
		"default-size":"Obnovit do základního nastavení",
		//views
		"edit-view":"Upravit",
		"remove-view":"Odstranit",
		"chart-edit":"Upravit graf",

		"chart-common":"Všeobecné",
		"chart-series":"Série",
		"chart-extras":"Doplňkové",

		"export-view":"Stažení",
		"export-view-pdf":"PDF dokument",
		"export-view-png":"Obrázek PNG",
		"export-view-excel":"Soubor Excel",

		"line-chart":"Lineární",
		"area-chart":"Oblast",
		"bar-chart":"Sloupcový",
		"donut-chart":"Kobliha",
		"pie-chart":"Výsečový",
		"radar-chart":"Radarový",
		"spline-chart":"Plošný",
		"splinearea-chart":"Plošný",

		"chart-axis":"Osa",
		"chart-scale":"Mřížka grafu",
		"chart-scale-color":"Barva síťky",
		"chart-xAxis-title":"Název osy X",
		"chart-yAxis-title":"Název osy Y",
		"chart-col-xAxis":"Levý sloupec použijte jako osa x",
		"chart-row-xAxis":"Použijte horní řádek jako osu x",
		"chart-xAxis-range":"x Rozsah osy",

		"chart-legend":"Legenda",
		"chart-row-legend":"Jako legendu použijte horní řádek",
		"chart-col-legend":"Jako legendu použijte levý sloupec",
		"chart-legend-range":"Rozsah legend",
		"chart-legend-align":"Zarovnat",
		"chart-legend-left":"Levý",
		"chart-legend-right":"Pravý",
		"chart-legend-center":"Centrum",
		"chart-legend-valign":"Svislé zarovnání",
		"chart-legend-top":"Horní",
		"chart-legend-middle":"Uprostřed",
		"chart-legend-bottom":"Dno",

		"chart-item":"Data",
		"stacked-chart":"Skládaný",
		"chart-range":"Rozsah",
		"chart-series-color":"Barva",
		"add-line":"Přidat řádek",
		"chart-type":"Typ",
		"chart-tooltip":"Tipy",

		"chart-data-from":"Datová řada z",
		"chart-columns":"sloupce",
		"chart-rows":"řádky",

		"chart-markers":"Tvary bodů",
		"chart-markers-square":"Čtverce",
		"chart-markers-triangle":"Trojúhelník",
		"chart-markers-diamond":"Diamanty",
		"chart-markers-round":"Kola",

		"chart-pie-text":"Zobrazit hodnoty uvnitř",
		"chart-pie-3d":"3D",

		"chart-radar-circle":"Circled lines"
	},
	tooltips: {
		"color": "Barva fontu",
		"background": "Barva pozadí",
		"font-family": "Písmo",
		"font-size": "Velikost písma",
		"text-align": "Zarovnejte vodorovně",
		"vertical-align": "Svislé zarovnání",
		"borders": "Hranice",
		"borders-no": "Žádná hrana",
		"borders-left": "Levý okraj",
		"borders-top": "Horní hrana",
		"borders-right": "Pravý okraj",
		"borders-bottom": "Spodní okraj",
		"borders-all": "Všechny hrany",
		"borders-outer": "Vnější hrany",
		"borders-top-bottom": "Horní a dolní okraj",
		"borders-color": "Barva ohraničení",
		"align-left": "Zarovnání doleva",
		"align-center": "Centrum",
		"align-right": "Zarovnat doprava",
		"align-top": "Horní zarovnání",
		"align-middle": "Zarovnat střed",
		"align-bottom": "Zarovnání zdola",
		"span": "Spojit",
		"wrap": "Obtékání textu",
		"undo": "Zpět",
		"redo": "Opakovat",
		"format": "Formát čísla",
		"increase-decimals":"Zvětšujte desetinná místa",
		"decrease-decimals":"Snižte desetinná místa",
		"font-weight": "Tučně",
		"font-style": "Kurzíva",
		"text-decoration": "Zdůraznit",
		"hide-gridlines": "Skrýt / zobrazit mřížky",
		"hide-headers": "Skrýt / zobrazit záhlaví",
		"create-filter": "Vytvořit / odebrat filtry",
		"freeze-columns" : "Ukotvit / uvolnit sloupce",
		"add-range": "Nastavit název pro vybraný rozsah",
		"conditional": "Podmíněné formátování",
		"add-sheet": "Přidat list",
		"lock-cell": "Zamknout / odemknout buňku",
		"clear": "Vyčistit",
		"add-link": "Přidat odkaz",
		"row": "Řádky",
		"column": "Sloupce",
		"sheet": "List",
		"add-image": "Obraz",
		"add-sparkline": "Graf",
		"add-comment": "Komentář"
	},
	menus:{
		"remove-sheet": "Odebrat list",
		"rename-sheet": "Přejmenovat list",
		"file": "Soubor",
		"new": "Nový",
		"new-sheet": "Nový list",
		"excel-import": "Import z aplikace Excel",
		"excel-export": "Export do aplikace Excel",
		"sheet": "Listy",
		"copy-sheet": "Zkopírovat na nový list",
		"edit": "Upravit",
		"undo": "Zpět",
		"redo": "Opakovat",
		"columns": "Sloupce",
		"insert-column": "Vložit sloupec",
		"delete-column": "Smazat sloupec",
		"show-column": "Zobrazit sloupec",
		"hide-column": "Skrýt sloupec",
		"resize-column": "Změnit velikost sloupce",
		"rows": "Řádky",
		"insert-row": "Vložte řádek",
		"delete-row": "Smazat řádek",
		"show-row": "Zobrazit řádek",
		"hide-row": "Skrýt řádek",
		"resize-row": "Změnit velikost řádku",
		"insert": "Vložit",
		"conditional-format": "Podmíněné formátování",
		"clear": "Průhledná",
		"clear-value":"Hodnoty",
		"clear-style":"Styly",
		"clear-conditional-formats":"Podmíněné formátování",
		"clear-dropdown-editors":"Rozbalovací nabídky a filtry",
		"clear-comments":"Komentáře",
		"clear-all":"Všechno",
		"image": "Obraz",
		"add-image-cell":"Přidat do buňky",
		"add-image-top":"Přidejte výše uvedené buňky",
		"graph": "Graf",
		"add-sparkline":"Přidat do buňky",
		"add-chart":"Přidejte výše uvedené buňky",
		"data": "Data",
		"add-link": "Přidat odkaz",
		"add-range": "Pojmenované rozsahy",
		"sort": "Třídit",
		"sort-asc": "Třídit od A do Z",
		"sort-desc": "Roztřídit Z do A",
		"view": "Pohled",
		"freeze-columns": "Ukotvit / uvolnit sloupce",
		"freeze-rows": "Ukotvit / zrušit ukotvení řádků",
		"hide-gridlines": "Skrýt / zobrazit mřížky",
		"hide-headers": "Skrýt / zobrazit záhlaví",
		"create-filter": "Vytvořit / odebrat filtry",
		"add-dropdown": "Přidat rozbalovací nabídku",
		"lock-cell": "Zamknout / odemknout buňku",
		"print": "Tisk",
		"add-comment":"Komentář"
	},
	table:{
		"math-error":"#ERROR!",
		"math-ref-error":"#REF!",
		"format-error":"NESPRÁVNÝ FORMÁT"
	},
	liveEditor:{
		"edit":"Upravit:"
	},
	formats:{
		"dateFormat": "mm/dd/yyyy",
		"timeFormat": "hh:mm AM/PM",
		"longDateFormat": "dd mmmm yyyy",
		"fullDateFormat": "mm/dd/yyyy hh:mm AM/PM",
		"parseDateTime": "%m/%d/%Y %G:%i:%s",
		"parseDate": "%m/%d/%Y"
	}
};
