export default {
	labels:{
		// formats
		"common": "Général",
		"currency": "Monétaire",
		"number": "Numérique",
		"percent": "Pour cent",
		"date": "Date",
		"string": "Textuel",
		"custom-format": "Personnalisé",
		"decimal-places":"Décimales",
		"separator":"Séparateur de groupe",
		"negative":"Nombre négatif",
		"date-format":"Format de date",
		"format-docs":"Comment créer un format",
		// titles
		"undo-redo": "Annuler/Refaire",
		"font": "Police de caractère",
		"text": "Texte",
		"cell": "Cellule",
		"align": "Align",
		"format": "Nombre",
		"column": "Colonne",
		"borders": "Bords",
		"px": "px",
		"apply": "Appliquer",
		// popups and dialogs
		"cancel": "Annuler",
		"save": "Sauvegarder",
		// multisheets
		"sheet": "Feuille",
		// conditions
		"conditional-format": "Mise en forme conditionnelle",
		"condition": "Condition",
		"conditional-style": "Style",
		"conditional-operator": "Règle",
		"conditional-between":"Compris entre",
		"conditional-not-equal":"Inégal",
		// ranges
		"range": "L'étendue",
		"range-title": "L'étendue nommées",
		"range-name": "Nom",
		"range-cells": "L'étendue",
		"range-scope": "Feuille",
		"range-global": "Book",
		// images
		"image-or": "ou",
		"image-title": "Ajouter une image",
		"image-upload": "Sélectionnez le fichier à télécharger",
		"image-url": "URL (e.g. http://*)",
		// sparklines
		"sparkline-title": "Ajouter un sparkline",
		"sparkline-type": "Taper",
		"sparkline-range": "L'étendue",
		"sparkline-color": "Couleur",
		"sparkline-positive": "Positive",
		"sparkline-negative": "Negative",
		// custom format
		"format-title": "Définir le format",
		"format-pattern": "Modèle de format",
		//dropdown
		"dropdown-empty": "Cellules vides",
		"dropdown-title": "Ajouter une liste déroulante",
		"dropdown-range": "L'étendue",
		// confirm
		"ok": "OK",
		// import/export
		"import-title": "Importer",
		"import-not-support": "Désolé, votre navigateur ne prend pas en charge l'importation",
		"export-title": "Exportation",
		"export-name": "Nom du fichier xlsx",
		"export-all-sheets":"Exporter toutes les feuilles",
		// add link
		"link-title": "Ajouter un lien",
		"link-name": "Texte",
		"link-url": "URL",
		//images
		"image": "Image",
		"add-image-cell":"Ajouter à la cellule",
		"add-image-top":"Ajouter les cellules ci-dessus",
		//charts
		"graph": "Graphique",
		"add-sparkline":"Ajouter à la cellule",
		"add-chart":"Ajouter les cellules ci-dessus",
		//conditional format labels
		"display" : "Style",
		"value" : "Valeur",
		// confirm messages
		"range-remove-confirm": "Voulez-vous vraiment supprimer définitivement l'étendue?",
		"sheet-remove-confirm": "Êtes-vous sûr de vouloir supprimer définitivement la feuille?",
		"merge-cell-confirm":"Seule la valeur supérieure gauche restera après la fusion. Continuez?",
		"error-range": "La plage est incorrecte!",
		//print
		"print":"Imprimez",
		"print-title":"Avant d'imprimer..",
		"print-settings":"Réglages généraux",
		"print-paper":"Taille de papier",
		"print-layout":"Disposition",
		"sheets":"Les feuilles",
		"selection":"Cellules sélectionnées",
		"borderless":"Masquer le quadrillage",
		"sheet-names":"Afficher les noms de feuille",
		"skip-rows":"Ignorer les lignes vides",
		"margin":"Masquer les marges",
		"page-letter":"Lettre",
		"page-a4":"A4 (210x297mm)",
		"page-a3":"A3 (297x420mm)",
		"page-width":"Largeur de page",
		"page-actual":"Taille actuelle",
		"page-portrait":"Verticale",
		"page-landscape":"Horizontale",
		//comment
		"comment":"Commenter",
		//resize
		"width":"Largeur",
		"height":"Hauteur",
		"fit-content": "Ajuster au contenu",
		"default-size":"Réinitialiser à la valeur par défaut",
		//views
		"edit-view":"Éditer",
		"remove-view":"Supprimer",
		"chart-edit":"Modifier le graphique",

		"chart-common":"Général",
		"chart-series":"Séries",
		"chart-extras":"Supplémentaire",

		"export-view":"Télécharger",
		"export-view-pdf":"Document PDF",
		"export-view-png":"Image PNG",
		"export-view-excel":"Fichier Excel",

		"line-chart":"Graphique linéaire",
		"area-chart":"Graphique en aires",
		"bar-chart":"Diagramme à bandes",
		"donut-chart":"Graphique en anneau",
		"pie-chart":"Diagramme circulaire",
		"radar-chart":"Carte radar",
		"spline-chart":"Diagramme Spline",
		"splinearea-chart":"Diagramme Spline",

		"chart-axis":"Axe",
		"chart-scale":"Lignes",
		"chart-scale-color":"Couleur de la ligne",
		"chart-xAxis-title":"Titre de l'axe X",
		"chart-yAxis-title":"Titre de l'axe Y",
		"chart-col-xAxis":"Utiliser la colonne de gauche comme axe des x",
		"chart-row-xAxis":"Utiliser la rangée du haut comme axe x",
		"chart-xAxis-range":"x Gamme d'axes",

		"chart-legend":"Légende",
		"chart-row-legend":"Utiliser la ligne du haut comme légende",
		"chart-col-legend":"Utiliser la colonne de gauche comme légende",
		"chart-legend-range":"Gamme Legend",
		"chart-legend-align":"Aligner",
		"chart-legend-left":"Gauche",
		"chart-legend-right":"Droite",
		"chart-legend-center":"Centre",
		"chart-legend-valign":"Alignement vertical",
		"chart-legend-top":"En haut",
		"chart-legend-middle":"Au milieu",
		"chart-legend-bottom":"En bas",

		"chart-item":"Donnés",
		"stacked-chart":"Cumulé",
		"chart-range":"L'étendue",
		"chart-series-color":"Couleur",
		"add-line":"Ajouter une ligne",
		"chart-type":"Taper",
		"chart-tooltip":"Conseils",

		"chart-data-from":"Série de données de",
		"chart-columns":"colonnes",
		"chart-rows":"lignes",

		"chart-markers":"Marqueurs de graphique",
		"chart-markers-square":"Carré",
		"chart-markers-triangle":"Triangle",
		"chart-markers-diamond":"Diamond",
		"chart-markers-round":"Rond",

		"chart-pie-text":"Afficher les valeurs à l'intérieur",
		"chart-pie-3d":"3D",

		"chart-radar-circle":"Lignes cerclées"
	},
	tooltips: {
		"color": "Couleur de la police",
		"background": "Couleur de l'arrière plan",
		"font-family": "De polices",
		"font-size": "Taille de police",
		"text-align": "Alignement horizontal",
		"vertical-align": "Alignement vertical",
		"borders": "Limites",
		"borders-no": "Pas de frontière",
		"borders-left": "Bord gauche",
		"borders-top": "Bordure supérieure",
		"borders-right": "Bordure droite",
		"borders-bottom": "Bordure inférieure",
		"borders-all": "Toutes les frontières",
		"borders-outer": "Bordures extérieures",
		"borders-top-bottom": "Bordures supérieure et inférieure",
		"borders-color": "Couleur de la bordure",
		"align-left": "Aligner à gauche",
		"align-center": "Aligner au centre",
		"align-right": "Aligner à droite",
		"align-top": "Aligner en haut",
		"align-middle": "Aligner au milieu",
		"align-bottom": "Aligner en bas",
		"span": "Fusionner",
		"wrap": "Habillage de texte",
		"undo": "Annuler",
		"redo": "Refaire",
		"format": "Format de nombre",
		"increase-decimals":"Augmenter les décimales",
		"decrease-decimals":"Diminuer les décimales",
		"font-weight": "Gras",
		"font-style": "Italique",
		"text-decoration": "Souligner",
		"hide-gridlines": "Masquer / afficher le quadrillage",
		"hide-headers": "Masquer / afficher les en-têtes",
		"create-filter": "Créer / supprimer des filtres",
		"freeze-columns" : "Figer / dégeler les colonnes",
		"add-range": "Définir le nom de la plage sélectionnée",
		"conditional": "Mise en forme conditionnelle",
		"add-sheet": "Ajouter une feuille",
		"lock-cell": "Verrouiller / déverrouiller la cellule",
		"clear": "Effacer",
		"add-link": "Ajouter un lien",
		"row": "Lignes",
		"column": "Colonnes",
		"sheet": "Feuille",
		"add-image": "Image",
		"add-sparkline": "Graphique",
		"add-comment": "Commenter"
	},
	menus:{
		"remove-sheet": "Supprimer la feuille",
		"rename-sheet": "Renommer la feuille",
		"file": "Fichier",
		"new": "Nouveau",
		"new-sheet": "Nouvelle feuille",
		"excel-import": "Importer depuis Excel",
		"excel-export": "Exporter vers Excel",
		"sheet": "Feuilles",
		"copy-sheet": "Copier sur une nouvelle feuille",
		"edit": "Éditer",
		"undo": "Annuler",
		"redo": "Refaire",
		"columns": "Colonnes",
		"insert-column": "Insérer une colonne",
		"delete-column": "Supprimer la colonne",
		"show-column": "Afficher la colonne",
		"hide-column": "Masquer la colonne",
		"resize-column": "Redimensionner la colonne",
		"rows": "Lignes",
		"insert-row": "Insérer une ligne",
		"delete-row": "Supprimer la ligne",
		"show-row": "Afficher la ligne",
		"hide-row": "Masquer la ligne",
		"resize-row": "Redimensionner la ligne",
		"insert": "Insérer",
		"conditional-format": "Format conditionnel",
		"clear": "Effacer",
		"clear-value":"Valeurs",
		"clear-style":"Style",
		"clear-conditional-formats":"Format conditionnel",
		"clear-dropdown-editors":"Liste déroulante et filtres",
		"clear-comments":"Commentaires",
		"clear-all":"Tout",
		"image": "Image",
		"add-image-cell":"Ajouter à la cellule",
		"add-image-top":"Ajouter les cellules ci-dessus",
		"graph": "Graphique",
		"add-sparkline":"Ajouter à la cellule",
		"add-chart":"Ajouter les cellules ci-dessus",
		"data": "Donnés",
		"add-link": "Ajouter un lien",
		"add-range": "L'étendue nommées",
		"sort": "Trier",
		"sort-asc": "Trier de A à Z",
		"sort-desc": "Trier de Z à A",
		"view": "Vue",
		"freeze-columns": "Figer / dégeler les colonnes",
		"freeze-rows": "Figer / dégeler les lignes",
		"hide-gridlines": "Masquer / afficher le quadrillage",
		"hide-headers": "Masquer / afficher les en-têtes",
		"create-filter": "Créer / supprimer des filtres",
		"add-dropdown": "Ajouter une liste déroulante",
		"lock-cell": "Verrouiller / déverrouiller la cellule",
		"print": "Impression",
		"add-comment":"Commenter"
	},
	table:{
		"math-error":"#ERROR!",
		"math-ref-error":"#REF!",
		"format-error":"FORMAT INCORRECT"
	},
	liveEditor:{
		"edit":"Edit:"
	},
	formats:{
		"dateFormat": "mm/dd/yyyy",
		"timeFormat": "hh:mm AM/PM",
		"longDateFormat": "dd mmmm yyyy",
		"fullDateFormat": "mm/dd/yyyy hh:mm AM/PM",
		"parseDateTime": "%m/%d/%Y %G:%i:%s",
		"parseDate": "%m/%d/%Y"
	}
};
