export default {
	labels:{
		// formats
		"common": "Ogólne",
		"currency": "Walutowe",
		"number": "Liczbowe",
		"percent": "Procentowe",
		"date": "Data",
		"string": "Tekstowe",
		"custom-format": "Niestandarowe",
		"decimal-places":"Miejsca dziesiętne",
		"separator":"Separator grup",
		"negative":"Liczba ujemna",
		"date-format":"Format daty",
		"format-docs":"Jak stworzyć format",
		// titles
		"undo-redo": "Cofnij/Ponów",
		"font": "Czcionka",
		"text": "Tekst",
		"cell": "Komórka",
		"align": "Wyrównanie",
		"format": "Liczba",
		"column": "Kolumna",
		"borders": "Obramowanie",
		"px": "px",
		"apply": "Zastosuj",
		// popups and dialogs
		"cancel": "Anuluj",
		"save": "Zapisz",
		// multisheets
		"sheet": "Arkusz",
		// conditions
		"conditional-format": "Formatowanie warunkowe",
		"condition": "Warunek",
		"conditional-style": "Styl",
		"conditional-operator": "Reguła",
		"conditional-between":"Pomiędzy",
		"conditional-not-equal":"Nierówne",
		// ranges
		"range": "Zakres",
		"range-title": "Nazwa ",
		"range-name": "Nazwa",
		"range-cells": "Zakres",
		"range-scope": "Arkusz",
		"range-global": "Book",
		// images
		"image-or": "lub",
		"image-title": "Dodaj zdjęcie",
		"image-upload": "Wybierz plik do wgrania",
		"image-url": "URL (e.g. http://*)",
		// sparklines
		"sparkline-title": "Dodaj wykres przebiegu w czasie",
		"sparkline-type": "Rodzaj",
		"sparkline-range": "Zakres",
		"sparkline-color": "Kolor",
		"sparkline-positive": "Positive",
		"sparkline-negative": "Negative",
		// custom format
		"format-title": "Ustaw format",
		"format-pattern": "Format pattern",
		//dropdown
		"dropdown-empty": "Puste komórki",
		"dropdown-title": "Dodaj rozwijaną listę",
		"dropdown-range": "Zakres",
		// confirm
		"ok": "OK",
		// import/export
		"import-title": "Import",
		"import-not-support": "Przepraszamy, Twoja przeglądarka nie pozwala importować",
		"export-title": "Export",
		"export-name": "Nazwa pliku xlsx",
		"export-all-sheets":"Eksportuj wszystkie arkusze",
		// add link
		"link-title": "Dodaj link",
		"link-name": "Tekst",
		"link-url": "URL",
		//images
		"image": "Obraz",
		"add-image-cell":"Dodaj do komórki",
		"add-image-top":"Dodaj powyżej komórki",
		//charts
		"graph": "Wykres",
		"add-sparkline":"Dodaj do komórki",
		"add-chart":"Dodaj powyżej komórki",
		//conditional format labels
		"display" : "Styl",
		"value" : "Wartość",
		// confirm messages
		"range-remove-confirm": "Czy na pewno chcesz trwale usunąć ten zakres?",
		"sheet-remove-confirm": "Czy na pewno chcesz trwale usunąć ten arkusz?",
		"merge-cell-confirm":"Po scaleniu pozostanie tylko lewa górna wartość. Kontynuować?",
		"error-range": "Zakres jest nieprawidłowy!",
		//print
		"print":"Drukuj",
		"print-title":"Zanim wydrukujesz..",
		"print-settings":"Ustawienia podstawowe",
		"print-paper":"Rozmiar papieru",
		"print-layout":"Układ",
		"sheets":"Arkusze",
		"selection":"Wybrane komórki",
		"borderless":"Ukryj linie siatki",
		"sheet-names":"Pokaż nazwy arkuszy",
		"skip-rows":"Pomiń puste wiersze",
		"margin":"Ukryj marginesy",
		"page-letter":"List",
		"page-a4":"A4 (210x297mm)",
		"page-a3":"A3 (297x420mm)",
		"page-width":"Szerokość strony",
		"page-actual":"Rzeczywisty rozmiar",
		"page-portrait":"Orientacja pionowa",
		"page-landscape":"Orientacja pozioma",
		//comment
		"comment":"Komentarz",
		//resize
		"width":"Szerokość",
		"height":"Wysokość",
		"fit-content": "Dopasuj do treści",
		"default-size":"Przywróć ustawienia domyślne",
		//views
		"edit-view":"Edytuj",
		"remove-view":"Usuń",
		"chart-edit":"Edytuj wykres",

		"chart-common":"Ogólne",
		"chart-series":"Serie",
		"chart-extras":"Dodatkowe",

		"export-view":"Pobierz",
		"export-view-pdf":"Dokument PDF",
		"export-view-png":"Obraz PNG",
		"export-view-excel":"Plik Excel",

		"line-chart":"Liniowy",
		"area-chart":"Obszar",
		"bar-chart":"Słupkowy",
		"donut-chart":"Pierścieniowy",
		"pie-chart":"Kołowy",
		"radar-chart":"Radarowy",
		"spline-chart":"Warstwowy",
		"splinearea-chart":"Warstowy",

		"chart-axis":"Oś",
		"chart-scale":"Siatka wykresu",
		"chart-scale-color":"Kolor siatki",
		"chart-xAxis-title":"Tytuł osi X",
		"chart-yAxis-title":"Tytuł osi Y",
		"chart-col-xAxis":"Użyj lewej kolumny jako osi X",
		"chart-row-xAxis":"Użyj górnego wiersza jako osi X",
		"chart-xAxis-range":"Zakres osi X",

		"chart-legend":"Legenda",
		"chart-row-legend":"Użyj górnego wiersza jako legendy",
		"chart-col-legend":"Użyj lewej kolumny jako legendy",
		"chart-legend-range":"Zakres legendy",
		"chart-legend-align":"Wyrównanie",
		"chart-legend-left":"Do lewej",
		"chart-legend-right":"Do prawej",
		"chart-legend-center":"Wyśrodkuj",
		"chart-legend-valign":"Wyrównaj w pionie",
		"chart-legend-top":"Na górze",
		"chart-legend-middle":"Pośrodku",
		"chart-legend-bottom":"Na dole",

		"chart-item":"Dane",
		"stacked-chart":"Skumulowany",
		"chart-range":"Zakres",
		"chart-series-color":"Kolor",
		"add-line":"Dodaj linię",
		"chart-type":"Typ",
		"chart-tooltip":"Podpowiedzi",

		"chart-data-from":"Seria danych z",
		"chart-columns":"kolumny",
		"chart-rows":"wiersze",

		"chart-markers":"Kształt punktów",
		"chart-markers-square":"Kwadraty",
		"chart-markers-triangle":"Trójkąty",
		"chart-markers-diamond":"Romby",
		"chart-markers-round":"Kółka",

		"chart-pie-text":"Pokaż wartości wewnątrz",
		"chart-pie-3d":"3D",

		"chart-radar-circle":"Circled lines"
	},
	tooltips: {
		"color": "Kolor czcionki",
		"background": "Kolor tła",
		"font-family": "Czcionka",
		"font-size": "Rozmiar czcionki",
		"text-align": "Wyrównaj w poziomie",
		"vertical-align": "Wyrównaj w pionie",
		"borders": "Obramowania",
		"borders-no": "Bez krawędzi",
		"borders-left": "Krawędź lewa",
		"borders-top": "Krawędź górna",
		"borders-right": "Krawędź prawa",
		"borders-bottom": "Krawędź dolna",
		"borders-all": "Wszystkie krawędzie",
		"borders-outer": "Krawędzie zewnętrzne",
		"borders-top-bottom": "Krawędź górna i dolna",
		"borders-color": "Kolor linii",
		"align-left": "Wyrównaj do lewej",
		"align-center": "Wyśrodkuj",
		"align-right": "Wyrównaj do prawej",
		"align-top": "Wyrównaj do góry",
		"align-middle": "Wyrównaj do środka",
		"align-bottom": "Wyrównaj do dołu",
		"span": "Scal",
		"wrap": "Zawijanie tekstu",
		"undo": "Cofnij",
		"redo": "Ponów",
		"format": "Format liczb",
		"increase-decimals":"Zwiększ dziesiętne",
		"decrease-decimals":"Zmniejsz dziesiętne",
		"font-weight": "Pogrubienie",
		"font-style": "Kursywa",
		"text-decoration": "Podkreślenie",
		"hide-gridlines": "Ukryj / pokaż linie siatki",
		"hide-headers": "Ukryj / pokaż nagłówki",
		"create-filter": "Utwórz / usuń filtry",
		"freeze-columns" : "Zablokuj / odblokuj kolumny",
		"add-range": "Ustaw nazwę dla wybranego zakresu",
		"conditional": "Formatowanie warunkowe",
		"add-sheet": "Dodaj arkusz",
		"lock-cell": "Zablokuj / odblokuj komórkę",
		"clear": "Wyczyść",
		"add-link": "Dodaj link",
		"row": "Wiersze",
		"column": "Kolumny",
		"sheet": "Arkusz",
		"add-image": "Obraz",
		"add-sparkline": "Wykres",
		"add-comment": "Komentarz"
	},
	menus:{
		"remove-sheet": "Usuń arkusz",
		"rename-sheet": "Zmień nazwę",
		"file": "Plik",
		"new": "Nowy",
		"new-sheet": "Nowy arkusz",
		"excel-import": "Importuj z Excela",
		"excel-export": "Eksport do Excela",
		"sheet": "Arkusze",
		"copy-sheet": "Skopiuj do nowego arkusza",
		"edit": "Edytuj",
		"undo": "Cofnij",
		"redo": "Ponów",
		"columns": "Kolumny",
		"insert-column": "Wstaw kolumnę",
		"delete-column": "Usuń kolumnę",
		"show-column": "Pokaż kolumnę",
		"hide-column": "Ukryj kolumnę",
		"resize-column": "Zmień rozmiar kolumny",
		"rows": "Wiersze",
		"insert-row": "Wstaw wiersz",
		"delete-row": "Usuń wiersz",
		"show-row": "Pokaż wiersz",
		"hide-row": "Ukryj wiersz",
		"resize-row": "Zmień rozmiar wiersza",
		"insert": "Wstaw",
		"conditional-format": "Formatowanie warunkowe",
		"clear": "Wyczyść",
		"clear-value":"Wartości",
		"clear-style":"Style",
		"clear-conditional-formats":"Formatowanie warunkowe",
		"clear-dropdown-editors":"Listy rozwijane i filtry",
		"clear-comments":"Komentarze",
		"clear-all":"Wszystko",
		"image": "Obraz",
		"add-image-cell":"Dodaj do komórki",
		"add-image-top":"Dodaj powyżej komórki",
		"graph": "Wykres",
		"add-sparkline":"Dodaj do komórki",
		"add-chart":"Dodaj powyżej komórki",
		"data": "Dane",
		"add-link": "Dodaj link",
		"add-range": "Nazwy zakresów",
		"sort": "Sortuj",
		"sort-asc": "Sortuj od A do Z",
		"sort-desc": "Sortuj od Z do A",
		"view": "Widok",
		"freeze-columns": "Zablokuj / odblokuj kolumny",
		"freeze-rows": "Zablokuj / odblokuj wiersze",
		"hide-gridlines": "Ukryj / pokaż linie siatki",
		"hide-headers": "Ukryj / pokaż nagłówki",
		"create-filter": "Utwórz / usuń filtry",
		"add-dropdown": "Dodaj listę rozwijaną",
		"lock-cell": "Zablokuj / odblokuj komórkę",
		"print": "Drukuj",
		"add-comment":"Komentarz"
	},
	table:{
		"math-error":"#ERROR!",
		"math-ref-error":"#REF!",
		"format-error":"NIEPRAWIDŁOWY FORMAT"
	},
	liveEditor:{
		"edit":"Edytuj:"
	},
	formats:{
		"dateFormat": "mm/dd/yyyy",
		"timeFormat": "hh:mm AM/PM",
		"longDateFormat": "dd mmmm yyyy",
		"fullDateFormat": "mm/dd/yyyy hh:mm AM/PM",
		"parseDateTime": "%m/%d/%Y %G:%i:%s",
		"parseDate": "%m/%d/%Y"
	}
};
