export default {
	labels:{
		// formats
		"common": "Общий",
		"currency": "Денежный",
		"number": "Числовой",
		"percent": "Проценты",
		"date":"Дата",
		"string":"Текст",
		"custom-format": "Свой формат",
		"decimal-places":"Десятичные знаки",
		"separator":"Разряды",
		"negative":"Отрицательное число",
		"currency-symbol":"Валюта",
		"date-format":"Формат даты",
		"format-docs":"Как создать свой формат",
		// titles
		"undo-redo": "Действие",
		"font": "Шрифты",
		"text": "Форматирование текста",
		"cell": "Стили ячейки",
		"align": "Положение текста",
		"format": "Формат",
		"column": "Колонка",
		"borders": "Границы",
		"px": "px",
		"apply": "Применить",
		// popups and dialogs
		"cancel": "Отменить",
		"save": "Сохранить",
		// multisheets
		"sheet": "Лист",
		// conditions
		"conditional-format": "Условное форматирование",
		"conditional-common": "общие",
		"conditional-text": "текст",
		"condition": "Условие",
		"conditional-style": "Стиль",
		"conditional-operator": "Оператор",
		"conditional-between":"между",
		"conditional-not-equal":"не равно",
		// ranges
		"range": "Диапазоны",
		"range-title": "Именованные диапазоны",
		"range-name": "Имя",
		"range-cells": "Диапазон",
		"range-scope": "Область",
		"range-global": "Книга",
		// images
		"image-or": "или",
		"image-title": "Добавить изображение",
		"image-upload": "Выбрать файл",
		"image-url": "URL ( http://*)",
		// sparklines
		"sparkline-title": "Добавить график",
		"sparkline-type": "Тип",
		"sparkline-range": "Диапазон",
		"sparkline-color": "Цвет",
		"sparkline-positive": "Положительные",
		"sparkline-negative": "Отрицательные",
		// custom format
		"format-title": "Формат",
		"format-pattern": "Схема формата",
		//dropdown
		"dropdown-empty": "Очистить ячейки",
		"dropdown-empty-option": "Пустой вариант",
		"dropdown-title": "Выпадающий список",
		"dropdown-range": "Диапазон",
		// confirm
		"ok": "Готово",
		// import/export
		"import-title": "Импортировать",
		"import-not-support": "Извините, ваш браузер не поддерживает импорт",
		"export-title": "Экспортировать",
		"export-name": "Имя .xslx файла",
		"export-all-sheets":"Экспортировать все листы",
		// add link
		"link-title": "Вставить ссылку",
		"link-name": "Текст",
		"link-url": "URL",
		//images
		"image": "Рисунок",
		"add-image-cell":"В ячейку",
		"add-image-top":"Над ячейками",
		//charts
		"graph": "График",
		"add-sparkline":"В ячейку",
		"add-chart":"Над ячейками",
		//controls
		"controls":"Контролы",
		"add-checkbox":"Чекбокс",
		"add-radio":"Радио группа",
		//conditional format labels
		"display" : "Стиль",
		"value" : "Значение",
		// confirm messages
		"range-remove-confirm": "Эту операцию нельзя отменить. Вы уверены?",
		"sheet-remove-confirm": "Эту операцию нельзя отменить. Вы уверены?",
		"merge-cell-confirm":"После объединения останется только верхнее левое значение. Продолжить?",
		"error-range": "Неверный диапазон!",
		"error-link": "Неверная ссылка!",
		//print
		"print":"Распечатать",
		"print-title":"Перед печатью..",
		"print-settings":"Основные настройки",
		"print-paper":"Размер бумаги",
		"print-layout":"Ориентация",
		"sheets":"Листы:",
		"selection":"Выбранные ячейки",
		"borderless":"Спрятать сетку",
		"sheet-names":"Имена листов",
		"skip-rows":"Пустые строки",
		"margin":"Спрятать отступы",
		"page-letter":"Letter",
		"page-a4":"A4 (210x297mm)",
		"page-a3":"A3 (297x420mm)",
		"page-width":"Ширина страницы",
		"page-actual":"Реальный размер",
		"page-portrait":"Вертикальная",
		"page-landscape":"Горизонтальная",
		"external-ui":"Внешние виджеты",
		"print-borders": "Показать границы печати",
		//comment
		"comment":"Комментировать",
		//resize
		"width":"Ширина",
		"height":"Высота",
		"fit-content": "Под контент",
		"default-size":"По умолчанию",
		//views
		"edit-view":"Редактировать",
		"remove-view":"Удалить",
		"chart-edit":"Редактор Графиков",

		"chart-common":"Основные",
		"chart-series":"Серии",
		"chart-extras":"Стилизация",

		"export-view":"Загрузить",
		"export-view-pdf":"PDF документ",
		"export-view-png":"PNG картинка",
		"export-view-excel":"Excel файл",

		"line-chart":"Линейный",
		"area-chart":"С областями",
		"bar-chart":"Столбчатый",
		"donut-chart":"Кольцевой",
		"pie-chart":"Круговой",
		"radar-chart":"Лепестковый",
		"spline-chart":"Сглаженный",
		"splinearea-chart":"Сглаженный с областями",
		"scatter-chart":"Точечный",

		"chart-scale":"Оси",
		"chart-x-axis":"Ось X",
		"chart-y-axis":"Ось Y",
		"chart-lines":"Линии",
		"chart-scale-color":"Цвет линий",
		"chart-xAxis-title":"Название",
		"chart-yAxis-title":"Название",
		"chart-col-xAxis":"Ось Х: левый столбец",
		"chart-col-yAxis":"Ось Y: левый столбец",
		"chart-row-xAxis":"Ось Х: верхний ряд",
		"chart-row-yAxis":"Ось Y: верхний ряд",
		"chart-xAxis-range":"Диапазон",
		"chart-yAxis-origin":"Начало",
		"chart-yAxis-start":"Старт",
		"chart-yAxis-end":"Конец",
		"chart-yAxis-step":"Шаг",
		"chart-yAxis-note":"* Установите все параметры, чтобы увидеть эффект",

		"chart-legend":"Легенда",
		"chart-row-legend":"Легенда: верхний ряд",
		"chart-col-legend":"Легенда: левый столбец",
		"chart-legend-range":"Диапазон легенды",
		"chart-legend-align":"По горизонтали",
		"chart-legend-left":"Слева",
		"chart-legend-right":"Справа",
		"chart-legend-center":"В центре",
		"chart-legend-valign":"По вертикали",
		"chart-legend-top":"Вверху",
		"chart-legend-middle":"По середине",
		"chart-legend-bottom":"Внизу",

		"chart-item":"Линия",
		"stacked-chart":"Накопление",
		"horizontal-chart":"Горизонтальный",
		"chart-range":"Диапазон",
		"chart-series-color":"Цвет",
		"add-line":"Добавить линию",
		"chart-type":"Тип",
		"chart-tooltip":"Подсказки",
		"chart-label":"Подписи",

		"chart-data-from":"Брать данные из",
		"chart-columns":"колонок",
		"chart-rows":"строк",

		"chart-markers":"Маркеры",
		"chart-markers-square":"Квадрат",
		"chart-markers-triangle":"Треугольник",
		"chart-markers-diamond":"Ромб",
		"chart-markers-round":"Круг",

		"chart-pie-3d":"3D",

		"chart-radar-circle":"Круговая граница",

		//validation
		"add-cell-validation": "Добавить проверку данных",
		"remove-cell-validation": "Очистить проверку данных",
		"highlight-invalid-data": "Обвести неверные данные",
		"remove-highlight-invalid-data": "Удалить обводку неверных данных",
		"validation-placeholder-text": "Текст",
		"validation-type": "Тип",
		"validation-any": "Любое значение",
		"validation-date": "Дата",
		"validation-number": "Число",
		"validation-text": "Текст",
		"validation-text-length": "Длина текста",
		"validation-range": "Внутри диапазона",
		"validation-integer": "Только целые",
		"validation-ignore-empty": "Игнорировать пустые",
		"validation-input-message": "Подсказка для ввода",
		"validation-error-title": "Заголовок ошибки",
		"validation-error-message": "Сообщение ошибки",
		"validation-error-handle": "Обработка ошибки",
		"validation-error-stop": "Остановить",
		"validation-error-warning": "Предупреждение",
		"validation-error-information": "Сообщение",
		"validation-error-title-text": "Ошибка",
		"validation-error-message-text": "Неверные данные!",
		"validation-error-save": "Сохранить",
		"validation-error-restore": "Восстановить",
		"find-replace-title": "Найти и Заменить",
		"find-title": "Найти",
		"find-what": "Найти:",
		"replace-with": "Заменить на:",
		"find-within": "Искать:",
		"find-sheet": "На листе",
		"find-book": "В книге",
		"find-match-case": "Учитывать регистр",
		"find-match-entire-content": "Ячейка целиком",
		"find-look-in": "Область поиска:",
		"find-formulas": "Формулы",
		"find-values": "Значения",
		"find-all-sheet": "Лист",
		"find-all-cell": "Ячейка",
		"find-all-value": "Значение",
		"find-all-formula": "Формула",
		"replace-all": "Заменить все",
		"replace": "Заменить",
		"find-all": "Найти все",
		"find-next": "Найти далее"
	},
	tooltips: {
		// "font" block
		"color": "Цвет текста",
		"background": "Цвет фона",
		"borders": "Границы",
		"borders-no": "Удалить границы",
		"borders-left": "Левая граница",
		"borders-top": "Верхняя граница",
		"borders-right": "Правая граница",
		"borders-bottom": "Нижняя граница",
		"borders-all": "Все границы",
		"borders-outer": "Внешние границы",
		"borders-top-bottom": "Верхняя и нижняя границы",
		"borders-color": "Цвет границы",
		"borders-line": "Линия границы",

		"add-sheet": "Вставить лист",
		"sheet": "Листы",
		"scale": "Масштаб",
		"show-sheet": "Показать лист",
	},
	menus: {
		"rename-sheet": "Переименовать лист",
		"copy-sheet": "Копировать в новый лист",
		"remove-sheet": "Удалить лист",
		"hide-sheet": "Спрятать лист",

		"new": "Новый",
		"common": "Общий",
		"text": "Текст",
		"graph": "График",
		"image": "Рисунок",
		"data": "Данные",
		"sort": "Сортировка",

		// "copy-paste" context menu
		"cut": "Вырезать",
		"copy": "Копировать",
		"paste": "Вставить",
		"special-paste": "Специальная вставка",
		"paste-values": "Значения",
		"paste-formulas": "Формулы",
		"paste-styles": "Стили",
		"paste-conditions": "Условное форматирование",
		"paste-validation": "Проверка данных",
	},
	actions: {
		// "file" block
		"file": "Файл",
		"sheet": "Листы",
		"new-sheet": "Новый лист",
		"copy-sheet": "Копировать в новый лист",
		"remove-sheet": "Удалить лист",
		"hide-sheet": "Спрятать лист",
		"excel-import": "Импортировать из Excel",
		"excel-export": "Экспортировать в Excel",
		"print": "Распечатать",
		"print-borders": "Спрятать/показать границы печати",

		// "undo-redo" block
		"undo-redo": "Действие",
		"undo": "Отменить",
		"redo": "Вернуть",

		// "font" block
		"font": "Шрифт",
		"font-family": "Шрифт",
		"font-weight": "Жирный",
		"font-style": "Курсив",
		"underline": "Подчеркнутый",
		"strike": "Перечеркнутый",
		"font-size": "Размер шрифта",

		// "align" block
		"align": "Выравнивание",
		"text-align": "Горизонтальное положение текста",
		"text-align-left": "Выровнять по левому краю",
		"text-align-center": "По центру",
		"text-align-right": "Выровнять по правому краю",
		"vertical-align": "Вертикальное положение текста",
		"vertical-align-top": "По верхнему краю",
		"vertical-align-middle": "Выровнять по середине",
		"vertical-align-bottom": "По нижнему краю",
		"span": "Объединить ячейки",
		"wrap": "Перенос текста",
		"increase-indent": "Увеличить отступ",
		"decrease-indent": "Уменьшить отступ",

		// "number" block
		"number": "Число",
		"format": "Выбрать числовой формат",
		"format-common": "Общий",
		"format-price": "Валюта",
		"format-int": "Число",
		"format-percent": "Процент",
		"format-date": "Дата",
		"format-string": "Текст",
		"format-custom": "Свой формат",
		"increase-decimals": "Увеличить число десятичных знаков",
		"decrease-decimals": "Уменьшить число десятичных знаков",

		// "edit" block
		"edit": "Редактирование",
		"sort-asc": "Сортировка от А до Я",
		"sort-desc": "Сортировка от Я до А",
		"create-filter": "Создать/удалить фильтры",
		"add-range": "Именованные диапазоны",
		"conditional-format": "Условное форматирование",
		"lock-cell": "Закрыть ячейку",
		"add-link": "Добавить ссылку",
		"add-dropdown": "Добавить выпадающий список",
		"clear": "Очистить",
		"clear-value": "Данные",
		"clear-style": "Стили",
		"clear-conditional-formats": "Условное форматирование",
		"clear-dropdown-editors": "Списки и фильтры",
		"clear-filters": "Фильтры",
		"clear-comments": "Комментарии",
		"clear-all": "Всё",
		"validation": "Проверка данных",
		"add-cell-validation": "Добавить проверку данных",
		"remove-cell-validation": "Очистить проверку данных",
		"highlight-invalid-data": "Обвести неверные данные",
		"remove-highlight-invalid-data": "Удалить обводку неверных данных",
		"find": "Найти и Заменить",

		// "insert" block
		"insert": "Вставка",
		"image": "Рисунок",
		"add-image": "Рисунок",
		"add-image-cell": "В ячейку",
		"add-image-top": "Над ячейками",
		"graph": "График",
		"add-sparkline": "В ячейку",
		"add-chart": "Над ячейками",
		"add-comment": "Комментировать",
		"controls": "Контролы",
		"add-checkbox": "Чекбокс",
		"add-radio": "Радио группа",

		// "view" block
		"view": "Вид",
		"row": "Строки",
		"add-row": "Вставить строку",
		"del-row": "Удалить строку",
		"show-row": "Показать строку",
		"hide-row": "Спрятать строку",
		"resize-row": "Изменить высоту",
		"format-row":"Формат строки",
		"column": "Столбцы",
		"add-column": "Вставить столбец",
		"del-column": "Удалить столбец",
		"show-column": "Показать столбец",
		"hide-column": "Спрятать столбец",
		"resize-column": "Изменить ширину",
		"format-column":"Формат столбца",
		"hide-gridlines": "Спрятать/показать сетку",
		"hide-headers": "Спрятать/показать заголовки",
		"freeze-rows": "Закрепить строки",
		"freeze-columns": "Закрепить столбцы",
		"show-formulas": "Спрятать/показать формулы",

		// "other" block
		"other": "Другое",
		"find-readonly": "Найти"
	},

	table:{
		"math-error":"#ОШИБКА!",
		"math-ref-error":"#ССЫЛКА!",
		"format-error":"ОШИБКА В ФОРМАТЕ",
		"math-xss-error": "XSS уязвимость!"
	},
	liveEditor:{
		"edit":"Правка:",
		"date": "Дата и время",
		"number": "Числовые",
		"text": "Текстовые",
		"financial": "Финансовые",
		"array": "Массива",
		"common": "Общие",
		"search": "Поиск",
		"category": "Категория"
	},
	formats:{
		"dateFormat": "dd.mm.yyyy",
		"timeFormat": "hh:mm",
		"longDateFormat": "dd mmmm yyyy",
		"fullDateFormat": "dd.mm.yyyy hh:mm",
		"parseDateTime": "%d.%m.%Y %G:%i:%s",
		"parseDate": "%d.%m.%Y",
		"currencies": [
			"${obj}",
			"{obj} €",
			"¥{obj}",
			"R$ {obj}"
		]
	}
};
