export default {
	labels:{
		// formats
		"common": "Общий",
		"currency": "Денежный",
		"number": "Числовой",
		"percent": "Проценты",
		// titles
		"undo-redo": "Действие",
		"font": "Шрифты",
		"text": "Форматирование текста",
		"cell": "Стили ячейки",
		"align": "Положение текста",
		"format": "Формат",
		"column": "Колонка",
		"borders": "Границы",
		"px": "px",
		"apply": "Готово",
		// popups and dialogs
		"cancel": "Отменить",
		"save": "Сохранить",
		// multisheets
		"sheet": "Лист",
		// conditions
		"conditional-format": "Условное форматирование",
		"condition": "Условие",
		"conditional-value": "Значение",
		"conditional-style": "Стиль",
		"conditional-between":"между",
		"conditional-not-equal":"не равно",
		// ranges
		"range": "Диапазоны",
		"range-title": "Именованные диапазоны",
		"range-name": "Имя",
		"range-cells": "Диапазон",
		// images
		"image-or": "или",
		"image-title": "Добавить изображение",
		"image-upload": "Выбрать файл",
		"image-url": "URL ( http://*)",
		// sparklines
		"sparkline-title": "Добавить график",
		"sparkline-type": "Тип",
		"sparkline-range": "Диапазон",
		"sparkline-color": "Цвет",
		"sparkline-positive": "Положительные",
		"sparkline-negative": "Отрицательные",
		// custom format
		"format-title": "Формат",
		"format-pattern": "Схема формата",
		//dropdown
		"dropdown-empty": "Очистить ячейки",
		"dropdown-title": "Выпадающий список",
		"dropdown-range": "Диапазон",
		// confirm
		"ok": "Готово",
		// import/export
		"import-title": "Импортировать",
		"import-not-support": "Извините, ваш браузер не поддерживает импорт",
		"export-title": "Экспортировать",
		"export-name": "Имя .xslx файла",
		"export-all-sheets":"Экспортировать все листы",
		// add link
		"link-title": "Вставить ссылку",
		"link-name": "Текст",
		"link-url": "URL",
		//images
		"image": "Рисунок",
		"graph": "График",
		//conditional format labels
		"display" : "Стиль",
		"value" : "Значение",
		// confirm messages
		"range-remove-confirm": "Эту операцию нельзя отменить. Вы уверены?",
		"sheet-remove-confirm": "Эту операцию нельзя отменить. Вы уверены?",
		"merge-cell-confirm":"После объединения останется только верхнее левое значение. Продолжить?",
		"error-range": "Неверный диапазон!",
		//print
		"print":"Распечатать",
		"print-title":"Перед печатью..",
		"print-settings":"Основные настройки",
		"print-paper":"Размер бумаги",
		"print-layout":"Ориентация",
		"current-sheet":"Акитвный лист",
		"all-sheets":"Все листы",
		"selection":"Выбранные ячейки",
		"borderless":"Спрятать сетку",
		"sheet-names":"Показывать имена листов",
		"skip-rows":"Пропустить пустые строки",
		"margin":"Спрятать отступы",
		"page-letter":"Letter",
		"page-a4":"A4 (210x297mm)",
		"page-a3":"A3 (297x420mm)",
		"page-width":"Ширина страницы",
		"page-actual":"Реальный размер",
		"page-portrait":"Вертикальная",
		"page-landscape":"Горизонтальная"
	},
	tooltips: {
		"color": "Цвет текста",
		"background": "Цвет фона",
		"font-family": "Шрифт",
		"font-size": "Размер шрифта",
		"text-align": "Горизонтальное положение текста",
		"vertical-align": "Вертикальное положение текста",
		"borders": "Границы",
		"borders-no": "Удалить границы",
		"borders-left": "Левая граница",
		"borders-top": "Верхняя граница",
		"borders-right": "Правая граница",
		"borders-bottom": "Нижняя граница",
		"borders-all": "Все границы",
		"borders-outer": "Внешние границы",
		"borders-top-bottom": "Верняя и нижняя границы",
		"borders-color": "Цвет границы",
		"align-left": "Выровнять по левому краю",
		"align-center": "По центру",
		"align-right": "Выровнять по правому краю",
		"align-top": "По верхнему краю",
		"align-middle": "Выровнять по середине",
		"align-bottom": "По нижнему краю",
		"span": "Объединить ячейки",
		"wrap": "Перенос текста",
		"undo": "Отменить",
		"redo": "Вернуть",
		"format": "Выбрать числовой формат",
		"font-weight": "Жирный",
		"font-style": "Курсив",
		"text-decoration": "Подчеркнутый",
		"hide-gridlines": "Спрятать/показать сетку",
		"hide-headers": "Спрятать/показать заголовки",
		"freeze-columns" : "Закрепить столбцы",		
		"add-range": "Имя выделенного диапазона",
		"conditional": "Условное форматирование",
		"add-sheet": "Вставить лист",
		"lock-cell": "Блокировать/Разблокировать ячейку",
		"clear": "Очистить",
		"add-link": "Вставить ссылку",
		"row": "Строки",
		"column": "Столбцы",
		"sheet": "Листы",		
	},
	menus:{
		"remove-sheet": "Удалить лист",
		"rename-sheet": "Переименовать лист",
		"file": "Файл",
		"new": "Новый",
		"new-sheet": "Новый лист",
		"excel-import": "Импортировать из Excel",
		"excel-export": "Экспортировать в Excel",
		"sheet": "Листы",		
		"copy-sheet": "Копировать в новый лист",
		"edit": "Редактирование",
		"undo": "Отменить",
		"redo": "Вернуть",
		"columns": "Столбцы",
		"insert-column": "Вставить столбец",
		"delete-column": "Удалить столбец",
		"show-column": "Показать столбец",
		"hide-column": "Спрятать столбец",
		"rows": "Строки",
		"insert-row": "Вставить строку",
		"delete-row": "Удалить строку",
		"show-row": "Показать строку",
		"hide-row": "Спрятать строку",
		"insert": "Вставка",
		"conditional-format": "Условное форматирование",
		"clear": "Очистить",
		"clear-value":"Данные",
		"clear-style":"Стили",
		"clear-conditional-formats":"Условное форматирование",
		"clear-dropdown-editors":"Списки и фильтры",
		"clear-all":"Всё",
		"add-image": "Рисунок",
		"add-sparkline": "График",
		"data": "Данные",
		"add-link": "Добавить ссылку",
		"add-range": "Именованные диапазоны",
		"sort": "Сортировка",
		"sort-asc": "Сортировка от А до Я",
		"sort-desc": "Сортировка от Я до А",
		"create-filter": "Создать фильтр",
		"view": "Вид",
		"freeze-columns": "Закрепить столбцы",
		"freeze-rows": "Закрепить строки",
		"hide-gridlines": "Спрятать/показать сетку",
		"hide-headers": "Спрятать/показать заголовки",
		"add-dropdown": "Добавить выпадающий список",
		"custom-format": "Задать числовой формат",
		"lock-cell": "Закрыть ячейку",
		"print": "Распечатать"
	}
};