export default {
	"Add members": "Add members",
	"Are you sure to leave this chat?": "Are you sure to leave this chat?",
	Avatar: "Avatar",
	"Are you sure to delete this member?": "Are you sure to delete this member?",
	Cancel: "Cancel",
	"Change avatar": "Change avatar",
	"Chat info": "Chat info",
	"Chat name": "Chat name",
	Chats: "Chats",
	"Create group": "Create group",
	Delete: "Delete",
	"Delete member": "Delete member",
	"Edit chat": "Edit chat",
	Leave: "Leave",
	"Leave chat": "Leave chat",
	member: "member",
	members: "members",
	Members: "Members",
	"New chat": "New chat",
	"No people to add": "No people to add",
	People: "People",
	Save: "Save",
	Search: "Search",
	"Show all members": "Show all members",
	Users: "Users",
	You: "You",
};
