export default {
	"Add members": "Добавить в чат",
	"Are you sure to leave this chat?": "Вы точно хотите выйти из чата?",
	Avatar: "Аватар",
	"Are you sure to delete this member?": "Вы точно хотите удалить участника?",
	Cancel: "Отменить",
	"Change avatar": "Изменить аватар",
	"Chat info": "О чате",
	"Chat name": "Имя чата",
	Chats: "Чаты",
	"Create group": "Создать группу",
	Delete: "Удалить",
	"Delete member": "Убрать участника",
	"Edit chat": "Редактировать",
	Leave: "Выйти",
	"Leave chat": "Покинуть чат",
	member: "участник",
	members: "участники",
	Members: "Участники",
	"New chat": "Новый чат",
	"No people to add": "Некого добавить",
	People: "Люди",
	Save: "Сохранить",
	Search: "Поиск",
	"Show all members": "Показать всех",
	Users: "Участники",
	You: "Вы",
	Ringing: "Звонок...",
	"Active call": "Активный звонок",
	"Is calling you": "Звонит Вам...",
	Accept: "Принять",
	Reject: "Отклонить",
	"Start call": "Начать звонок",
	"Join call": "Присоединиться к звонку",
	"End call": "Завершить звонок",
	"Ended call": "Звонок завершён",
	"Incoming call": "Входящий звонок",
	"Outgoing call": "Исходящий звонок",
	"Rejected call": "Отклонённый звонок",
	"Missed call": "Пропущенный звонок",
	"Can't start the call": "Ошибка при создании звонка",
	"Could not find your": "Не обнаружен(а)",
	"Error opening your": "Ошибка подключения:",
	microphone: "микрофон",
	camera: "камера",
	Size: "Размер",
	B: "Б",
	KB: "КБ",
	MB: "МБ",
	GB: "ГБ",
	"File size exceeds the limit": "Размер файла превышает допустимый предел",
	"File upload error": "Ошибка загрузки файла",
};
