var zhLocale = {
	"Add members": "新增成员",
	"Are you sure to leave this chat?": "您确定要离开此聊天吗",
	Avatar: "头像",
	"Are you sure to delete this member?": "您确定要删除该成员",
	Cancel: "取消",
	"Change avatar": "更改头像",
	"Chat info": "聊天信息",
	"Chat name": "聊天名称",
	Chats: "聊天室",
	"Create group": "创建组",
	Delete: "删除",
	"Delete member": "删除会员",
	"Edit chat": "编辑聊天",
	Leave: "离开",
	"Leave chat": "离开聊天",
	member: "会员",
	members: "成员",
	Members: "成员",
	"New chat": "新聊天",
	"No people to add": "没有人要添加",
	People: "人",
	Save: "保存",
	Search: "搜索",
	"Show all members": "显示所有成员",
	Users: "用户数",
	You: "您",
	Ringing: "打电话...",
	"Active call": "当前通话",
	"Is calling you": "给你打电话...",
	Accept: "接听电话",
	Reject: "拒绝",
	"Start call": "开始通话",
	"Join call": "加入此通话",
	"End call": "结束这次通话",
	"Ended call": "通话结束",
	"Incoming call": "来电",
	"Outgoing call": "拨出电话",
	"Rejected call": "拒接电话",
	"Missed call": "未接来电",
	"Could not find your": "找不到",
	"Error opening your": "访问错误",
	microphone: "麦克风",
	camera: "摄像头",
};
