export default {
	Save: "Mentés",
	"Save all": "Az összes mentése",
	Rename: "Átnevezés",
	Open: "Nyitás",
	Edit: "Szerkesztés",
	Delete: "Törlés",
	Folder: "Mappa",
	"Add New": "Új hozzáadása",
	"My Files": "Saját fájlok",
	Size: "Méret",
	Date: "Dátum",
	"back to parent folder": "vissza a szülő mappához",
	Download: "Letöltés",
	Type: "Típus",
	Information: "Információ",
	Files: "Fájlok",
	Table: "Táblázat",
	Cards: "Kártyák",
	Total: "Összesen",
	"Are you sure ?": "Biztos vagy benne?",
	Details: "Részletek",
	"Enter a new name": "Adjon meg egy új nevet",
	Add: "Hozzáadás",
	"Select something": "Válasszon valamit",
	"Download file": "Fájl letöltése",
	Preview: "Előnézet",
	Refresh: "Frissítés",
	"Are you sure you want to exit without saving?":
	"Biztosan ki akar lépni mentés nélkül?",
	"Save before closing?": "Mentés bezárás előtt?",
	Copy: "Másolás",
	Cut: "Kivágás",
	Paste: "Beillesztés",
	"Deleting...": "Törlés...",
	"Copying...": "Másolás...",
	"Moving...": "Áthelyezés...",
	Folders: "Mappák",
	"Search results": "Keresési eredmények",
	"Search results in": "Keresési eredmények itt:",
	"Search files and folders": "Fájlok és mappák keresése",
	"Add new file": "Új fájl hozzáadása",
	"Add new folder": "Új mappa hozzáadása",
	"Upload file": "Fájl feltöltése",
	"Upload folder": "Mappa feltöltése",
	folder: "mappa",
	file: "fájl",
	archive: "archívum",
	audio: "hangfájl",
	image: "kép",
	video: "videó",
	code: "kód",
	document: "dokumentum",
	of: "ból",
	used: "használt",
	"Open item location": "Elem helyének megnyitása",
	"Are you sure you want to delete": "Biztosan törölni szeretné",
	"these items:": "ezeket az elemeket:",
	"this item:": "ezt az elemet:",
	"Delete files": "Fájlok törlése",
	and: "és",
	"more file(s)": "további fájl(oka)t",
	"Close the editor": "Szerkesztő bezárása",
	"Close this file": "Fájl bezárása",
};