var ruLocale = {
	Files: "Файлы",
	"My Files": "Моя полка",
	Email: "Почта",
	Save: "Сохранить",
	Rename: "Переименовать",
	Open: "Открыть",
	Edit: "Редактировать",
	Delete: "Удалить",
	Folder: "Папка",
	"Add New": "Добавить",
	Size: "Размер",
	Date: "Дата",
	"back to parent folder": "наверх",
	Download: "Скачать",
	Type: "Тип",
	Remove: "Удалить",
	Table: "Таблица",
	Cards: "Карточки",
	Total: "Разделенный экран",
	"Are you sure ?": "Вы уверены？",
	Details: "Детали",
	"Enter a new name": "Новое имя",
	Add: "Добавить",
	"Select something": "Выберите файл или папку",
	"Download file": "Скачать файл",
	Preview: "Превью",
	Refresh: "Обновить",
	"Are you sure you want to exit without saving?":
		"Вы точно хотите выйти из редактора, не сохранив изменения?",
	Copy: "Копировать",
	Cut: "Вырезать",
	Paste: "Вставить",
};
