var zhLocale = {
	Email: "电子邮件",
	Save: "保存",
	Rename: "改名",
	Open: "打开",
	Edit: "编辑",
	Delete: "删除",
	Folder: "卷宗",
	"Add New": "添新",
	"My Files": "我的文件",
	Size: "尺寸",
	Date: "日期",
	"back to parent folder": "回到上层资料夹",
	Download: "下载",
	"View or edit file": "查看或编辑文件",
	Type: "类型",
	Actions: "行动",
	Remove: "清除",
	"Email expected, but found:": "预期发送电子邮件，但找到:",
	Files: "档案",
	Table: "表",
	Cards: "牌",
	Total: "总",
	"Are you sure ?": "你确定吗 ？",
	Details: "细节",
	"Enter a new name": "输入新名称",
	Add: "加",
	"Select something": "选择某物",
	"Download file": "下载文件",
	Preview: "文件预览",
	Refresh: "刷新",
	"Are you sure you want to exit without saving?": "您确定要不保存就退出吗？",
	Copy: "复制",
	Cut: "切",
	Paste: "贴",
};
