export default {
	Save: "保存",
	"Save all": "保存全部",
	Rename: "重新命名",
	Open: "打开",
	Edit: "编辑",
	Delete: "删除",
	Folder: "文件夹",
	"Add New": "新建...",
	"My Files": "我的文件",
	Size: "大小",
	Date: "修改日期",
	"back to parent folder": "返回上级",
	Download: "下载",
	Type: "类型",
	Information: "信息",
	Files: "文件",
	Table: "列表模式",
	Cards: "图标模式",
	Total: "分栏模式",
	"Are you sure ?": "你确定吗 ？",
	Details: "明细",
	"Enter a new name": "输入文件(夹)名称",
	Add: "添加",
	"Select something": "选择……",
	"Download file": "下载文件",
	Preview: "预览",
	Refresh: "刷新",
	"Are you sure you want to exit without saving?": "您确定要不保存就退出吗？",
	"Save before closing?": "关闭前保存？",
	Copy: "复制",
	Cut: "剪切",
	Paste: "粘贴",
	"Deleting...": "删除中……",
	"Copying...": "复制中……",
	"Moving...": "移动中……",
	Folders: "文件夹",
	"Search results": "搜索结果",
	"Search results in": "文件夹中的搜索结果",
	"Search files and folders": "搜索文件和文件夹",
	"Add new file": "新建文本文件",
	"Add new folder": "新建文件夹",
	"Upload file": "上传文件",
	folder: "文件夹",
	file: "文件",
	archive: "压缩文件",
	audio: "音频",
	image: "图片",
	video: "视频",
	code: "代码",
	document: "文档",
	of: "已用/",
	used: "总计",
	"Open item location": "打开位置",
	"Are you sure you want to delete": "你确定你要删除",
	"these items:": "这些文件:",
	"this item:": "这个文件:",
	"Delete files": "删除文件",
	and: "和",
	"more file(s)": "更多文件",
	"Close the editor": "关闭编辑器",
	"Close this file": "关闭这个文件",
};
