export default {
	Favorite: "Favorite",
	Recent: "Recent",
	Shared: "Shared",
	Trash: "Trash",
	"Add to favorites": "Add to favorites",
	"Remove from favorites": "Remove from favorites",
	Share: "Share",
	Tags: "Tags",
	Comments: "Comments",
	"Can view": "Can view",
	"Can edit": "Can edit",
	"Share File": "Share File",
	"Invite someone...": "Invite someone...",
	Invite: "Invite",
	Restore: "Restore",
	"Delete from trash": "Delete from trash",
	"Restoring...": "Restoring...",
	"Empty trash": "Empty trash",
	"back to ": "back to ",
	"Select a user": "Select a user",
	"Add a tag": "Add a tag",
	"No comments yet": "No comments yet",
	"No users": "No users",
	"Available to": "Available to",
	"user(s)": "user(s)",
	"Manage Tags": "Manage Tags",
	"Press Enter to create a new tag": "Press Enter to create a new tag",
	"Click Add to create a new tag": "Click Add to create a new tag",
	"Open tag settings": "Open tag settings",
	"Type to search a tag": "Type to search a tag",
	"Show version history": "Show version history",
	"Last edited at": "Last edited at",
	"Last edited on": "Last edited on",
	"Back to editor": "Back to editor",
	"Version history": "Version history",
	"Show changes": "Show changes",
	"Restored from": "Restored from",
	"Restore this version": "Restore this version",
	// inherited from the File Manager
	Save: "Save",
	Rename: "Rename",
	Open: "Open",
	Edit: "Edit",
	Delete: "Delete",
	Folder: "Folder",
	"Add New": "Add New",
	"My Files": "My Files",
	Size: "Size",
	Date: "Date",
	"back to parent folder": "back to parent folder",
	Download: "Download",
	Type: "Type",
	Information: "Information",
	Files: "Files",
	Table: "Table",
	Cards: "Cards",
	Total: "Total",
	"Are you sure ?": "Are you sure ?",
	Details: "Details",
	"Enter a new name": "Enter a new name",
	Add: "Add",
	"Select something": "Select something",
	"Download file": "Download file",
	Preview: "Preview",
	Refresh: "Refresh",
	"Are you sure you want to exit without saving?":
		"Are you sure you want to exit without saving?",
	Copy: "Copy",
	Cut: "Cut",
	Paste: "Paste",
	"Deleting...": "Deleting...",
	"Copying...": "Copying...",
	"Moving...": "Moving...",
	Folders: "Folders",
	"Search results": "Search results",
	"Search results in": "Search results in",
	"Search files and folders": "Search files and folders",
	"Add new file": "Add new file",
	"Add new folder": "Add new folder",
	"Upload file": "Upload file",
	folder: "folder",
	file: "file",
	archive: "archive",
	audio: "audio",
	image: "image",
	video: "video",
	code: "code",
	document: "document",
	of: "of",
	used: "used",
};