export default {
	Favorite: "Избранные",
	Recent: "Недавние",
	Shared: "Общие",
	Trash: "Корзина",
	"Add to favorites": "В избранное",
	"Remove from favorites": "Удалить из избранного",
	Share: "Расшарить",
	Tags: "Теги",
	Comments: "Комментарии",
	"Can view": "Редактирование",
	"Can edit": "Просмотр",
	"Share File": "Поделиться файлом",
	"Invite someone...": "Пригласить пользователя...",
	Invite: "Пригласить",
	Restore: "Восстановить",
	"Delete from trash": "Удалить из корзины",
	"Restoring...": "Восстанавливаем...",
	"Empty trash": "Удалить все",
	"back to ": "назад к ",
	"Select a user": "Выберите пользователя",
	"Add a tag": "Добавьте теги",
	"No comments yet": "Пока здесь ничего нет",
	"No users": "Нет пользователей",
	"Available to": "Файл доступен",
	"user(s)": "пользователям",
	"Manage Tags": "Редактирование тегов",
	"Press Enter to create a new tag": "Нажмите Enter, чтобы создать новый тег",
	"Click Add to create a new tag": "Нажмите Add, чтобы создать новый тег",
	"Open tag settings": "Открыть настройки тегов",
	"Type to search a tag": "Искать тег",
	"Show version history": "История изменений",
	"Last edited on": "Последнее редактирование",
	"Last edited at": "Последнее редактирование в",
	"Back to editor": "Назад в редактор",
	"Version history": "История редактирования",
	"Show changes": "Показать изменения",
	"Restored from": "Восстановлено из",
	"Restore this version": "Восстановить эту версию",
	// inherited from the File Manager
	Save: "Сохранить",
	"Save all": "Сохранить всё",
	Rename: "Переименовать",
	Open: "Открыть",
	Edit: "Редактировать",
	Delete: "Удалить",
	Folder: "Папка",
	"Add New": "Добавить",
	"My Files": "Моя полка",
	Size: "Размер",
	Date: "Дата",
	"back to parent folder": "наверх",
	Download: "Скачать",
	Type: "Тип",
	Information: "Инфо",
	Files: "Файлы",
	Table: "Таблица",
	Cards: "Карточки",
	Total: "Две таблицы",
	"Are you sure ?": "Вы уверены？",
	Details: "Детали",
	"Enter a new name": "Новое имя",
	Add: "Добавить",
	"Select something": "Выберите файл или папку",
	"Download file": "Скачать файл",
	Preview: "Превью",
	Refresh: "Обновить",
	"Are you sure you want to exit without saving?":
		"Вы хотите выйти из редактора, не сохранив изменения?",
	"Save before closing?": "Сохранить перез закрытием?",
	Copy: "Копировать",
	Cut: "Вырезать",
	Paste: "Вставить",
	"Deleting...": "Удаляем...",
	"Copying...": "Копируем...",
	"Moving...": "Перемещаем...",
	Folders: "Папки",
	"Search results": "Результаты поиска",
	"Search results in": "Результаты поиска в",
	"Search files and folders": "Искать файлы и папки",
	"Add new file": "Добавить файл",
	"Add new folder": "Добавить папку",
	"Upload file": "Загрузить файл",
	folder: "папка",
	file: "файл",
	archive: "архив",
	audio: "аудиофайл",
	image: "изображение",
	video: "видео",
	code: "текстовый файл",
	document: "документ",
	of: "из",
	used: "занято",
	"Open item location": "Открыть в папке",
	"Are you sure you want to delete": "Вы хотите удалить",
	"these items:": "следующие элементы:",
	"this item:": "этот элемент:",
	"Delete files": "Удалить файлы",
	and: "и",
	"more file(s)": "файл(ов)",
	"Close the editor": "Закрыть редактор",
	"Close this file": "Закрыть этот файл",
};