export default {
	Favorite: "我的收藏",
	Recent: "最近使用",
	Shared: "我的分享",
	Trash: "废纸篓",
	"Add to favorites": "添加到我的收藏",
	"Remove from favorites": "从我的收藏中删除",
	Share: "分享",
	Tags: "标签",
	Comments: "评论",
	"Can view": "可查看",
	"Can edit": "可编辑",
	"Share File": "分享文件",
	"Invite someone...": "邀请某人...",
	Invite: "邀请",
	"Add a tag": "添加标签",
	Restore: "还原",
	"Delete from trash": "立即删除...",
	"Restoring...": "放回原处",
	"Empty trash": "清空垃圾桶",
	"back to ": "回到",
	"Select a user": "选择用户",
	"No comments yet": "暂时没有评论",
	"No users": "没有使用者",
	"Available to": "有空",
	"user(s)": "用户",
	"Open item location": "打开位置",
	"Manage Tags": "管理标签",
	"Press Enter to create a new tag": "按【回车】键创建一个新标签。",
	"Click Add to create a new tag": "按【添加】按钮创建一个新标签。",
	"Open tag settings": "打开标签设置",
	"Type to search a tag": "输入搜索或添加标签",
	"Show version history": "显示版本历史",
	"Last edited on": "上次编辑是",
	"Last edited at": "上次编辑时间",
	"Back to editor": "返回编辑",
	"Version history": "版本历史",
	"Show changes": "显示变更",
	"Restored from": "从还原",
	"Restore this version": "还原到此版本",
	// inherited from the File Manager
	Save: "保存",
	"Save all": "保存全部",
	Rename: "重新命名",
	Open: "打开",
	Edit: "编辑",
	Delete: "删除",
	Folder: "文件夹",
	"Add New": "新建...",
	"My Files": "我的文件",
	Size: "大小",
	Date: "修改日期",
	"back to parent folder": "返回上级",
	Download: "下载",
	Type: "类型",
	Information: "信息",
	Files: "文件",
	Table: "列表模式",
	Cards: "图标模式",
	Total: "分栏模式",
	"Are you sure ?": "你确定吗 ？",
	Details: "明细",
	"Enter a new name": "输入文件(夹)名称",
	Add: "添加",
	"Select something": "选择……",
	"Download file": "下载文件",
	Preview: "预览",
	Refresh: "刷新",
	"Are you sure you want to exit without saving?": "您确定要不保存就退出吗？",
	"Save before closing?": "关闭前保存？",
	Copy: "复制",
	Cut: "剪切",
	Paste: "粘贴",
	"Deleting...": "删除中……",
	"Copying...": "复制中……",
	"Moving...": "移动中……",
	Folders: "文件夹",
	"Search results": "搜索结果",
	"Search results in": "文件夹中的搜索结果",
	"Search files and folders": "搜索文件和文件夹",
	"Add new file": "新建文本文件",
	"Add new folder": "新建文件夹",
	"Upload file": "上传文件",
	folder: "文件夹",
	file: "文件",
	archive: "压缩文件",
	audio: "音频",
	image: "图片",
	video: "视频",
	code: "代码",
	document: "文档",
	of: "已用/",
	used: "总计",
	"Open item location": "打开位置",
	"Are you sure you want to delete": "你确定你要删除",
	"these items:": "这些文件:",
	"this item:": "这个文件:",
	"Delete files": "删除文件",
	and: "和",
	"more file(s)": "更多文件",
	"Close the editor": "关闭编辑器",
	"Close this file": "关闭这个文件",
};