export default {
	"Add filter": "Voeg filter toe",

	in: "=",
	equal: "=",
	notEqual: "<>",
	less: "<",
	greater: ">",
	greaterOrEqual: ">=",
	lessOrEqual: "<=",
	contains: "bevat",
	notContains: "bevat niet",
	beginsWith: "begint met",
	notBeginsWith: "begint niet met",
	endsWith: "eindigt met",
	notEndsWith: "eindigt niet met",
	between: "tussen",
	notBetween: "niet tussen",

	and: "en",
	or: "of",
	Edit: "Bewerken",
	"Add Filter": "Voeg filter toe",
	"Add Group": "Voeg groep toe",
	Delete: "Verwijderen",
	Apply: "Toepassen",
	Cancel: "Annuleren",
};
