export default {
	"Add filter": "添加过滤器",

	in: "=",
	equal: "=",
	notEqual: "<>",
	less: "<",
	greater: ">",
	greaterOrEqual: ">=",
	lessOrEqual: "<=",
	contains: "包含",
	notContains: "不包含",
	beginsWith: "开始于",
	notBeginsWith: "不开始",
	endsWith: "结束",
	notEndsWith: "不是以",
	between: "之间",
	notBetween: "不在之间",

	and: "和",
	or: "要么",
	Edit: "编辑",
	"Add Filter": "添加过滤器",
	"Add Group": "添加组",
	Delete: "删除",
	Apply: "应用",
	Cancel: "取消",
};