export default {
	"Add task below": "Add task below",
	"Add subtask": "Add subtask",
	Indent: "Indent",
	Unindent: "Unindent",
	"Set due date": "Set due date",
	Priority: "Priority",
	Low: "Low",
	Medium: "Medium",
	High: "High",
	"Reset priority": "Reset priority",
	"Assign to": "Assign to",
	"Move to": "Move to",
	Duplicate: "Duplicate",
	Copy: "Copy",
	Paste: "Paste",
	Delete: "Delete",
	"Add project": "Add project",
	"Rename project": "Rename project",
	"Delete project": "Delete project",

	"No project": "No project",
	"Add task": "Add task",
	"New project": "New project",
	"Enter a description": "Enter a description",
	Search: "Search",

	Show: "Show",
	all: "all",
	active: "active",
	completed: "completed",

	"Sort by": "Sort by",
	"Text (a-z)": "Text (a-z)",
	"Text (z-a)": "Text (z-a)",
	"Priority (low to high)": "Priority (low to high)",
	"Priority (high to low)": "Priority (high to low)",
	"Due date (old to new)": "Due date (old to new)",
	"Due date (new to old)": "Due date (new to old)",

	"Delete task": "Delete task",
	"The task will be deleted permanently, are you sure?":
		"The task will be deleted permanently, are you sure?",
};
