export default {
	"Add task below": "Добавить задачу ниже",
	"Add subtask": "Добавить подзадачу",
	Indent: "Cмещение вправо",
	Unindent: "Cмещение влево",
	"Set due date": "Установить дату",
	"Assign to": "Назначить",
	"Move to": "Перенести",
	Duplicate: "Дублировать",
	Copy: "Копировать",
	Paste: "Вставить",
	Delete: "Удалить",
	"Add project": "Добавить проект",
	"Rename project": "Переименовать проект",
	"Delete project": "Удалить проект",

	"No project": "Без проекта",
	"Add task": "Добавить задачу",
	"New project": "Новый проект",
	"Enter a description": "Введите описание",
	Search: "Поиск",

	Show: "Видны",
	all: "все",
	active: "активные",
	completed: "завершенные",
};
