export default {
	"Add column": "Add column",
	"All reports": "All reports",
	"Are you sure to delete this report?": "Are you sure to delete this report?",
	"Are you sure to delete this query?": "Are you sure to delete this query?",
	Average: "Average",
	Cancel: "Cancel",
	Chart: "Chart",
	Column: "Column",
	Columns: "Columns",
	"Color column": "Color column",
	Common: "Common",
	"Copy of": "Copy of",
	Count: "Count",
	"Created on": "Created on",
	Data: "Data",
	"Data source": "Data source",
	Day: "Day",
	Delete: "Delete",
	"Delete report": "Delete report",
	Description: "Description",
	Query: "Query",
	Edit: "Edit",
	"Enter query name": "Enter query name",
	Export: "Export",
	"To Excel": "To Excel",
	"To CSV": "To CSV",
	"To PNG": "To PNG",
	"To PDF": "To PDF",
	Filter: "Filter",
	"Filtering query": "Filtering query",
	"Frozen columns above": "Frozen columns above",
	Function: "Function",
	Group: "Group",
	"Group summaries": "Group summaries",
	"Join data": "Join data",
	Heatmap: "Heatmap",
	"Labels column": "Labels column",
	Max: "Max",
	Min: "Min",
	Month: "Month",
	New: "New",
	"Click 'New' button to add a new report":
		"Click 'New' button to add a new report",
	"Select any report from the list": "Select any report from the list",
	"No reports": "No reports",
	"No saved queries": "No saved queries",
	"Last modified": "Last modified",
	"New column name": "New column name",
	"New report": "New report",
	"Please delete the related query filter first":
		"Please delete the related query filter first",
	"Please delete the related group rule first":
		"Please delete the related group rule first",
	Rename: "Rename",
	"Report name": "Report name",
	Reports: "Reports",
	Save: "Save",
	"Save query": "Save query",
	Sort: "Sort",
	"Specify columns to group by and output(s)":
		"Specify columns to group by and output(s)",
	"Specify columns to sort by": "Specify columns to sort by",
	Sum: "Sum",
	Table: "Table",
	Title: "Title",
	"Type to search": "Type to search",
	View: "View",
	Year: "Year",
	//chart
	Axes: "Axes",
	"X Axis": "X Axis",
	"Y Axis": "Y Axis",
	columns: "columns",
	rows: "rows",
	"Data series": "Data series",
	"Chart type": "Chart type",
	"Keys column": "Keys column",
	"X axis column": "X axis column",
	"Values column": "Values column",
	Color: "Color",
	"Marker type": "Marker type",
	"Fill marker": "Fill marker",
	Legend: "Legend",
	"Logarithmic scale": "Logarithmic scale",
	Gridlines: "Gridlines",
	Bottom: "Bottom",
	None: "None",
	Right: "Right",
	Line: "Line",
	Spline: "Spline",
	Area: "Area",
	"Stacked area": "Stacked area",
	"Spline area": "Spline area",
	Bar: "Bar",
	"Stacked bar": "Stacked bar",
	Radar: "Radar",
	Pie: "Pie",
	Donut: "Donut",
	"Create copy": "Create copy",
	circle: "circle",
	square: "square",
	triangle: "triangle",
	diamond: "diamond",
	"no markers": "no markers",
	"Vertical labels": "Vertical labels",
	"Extract series from": "Extract series from",
	True: "True",
	False: "False",
	"Save filter to use it in other reports":
		"Save filter to use it in other reports",
	"No filter": "No filter",
	Text: "Text",
	Select: "Select",
};