export default {
	"Add column": "Добавить колонку",
	"All reports": "Все отчеты",
	"Are you sure to delete this report?":
		"Вы уверены, что хотите удалить этот отчет?",
	"Are you sure to delete this query?":
		"Вы уверены, что хотите удалить этот фильтр?",
	Average: "Средн",
	Cancel: "Отмена",
	Chart: "Диаграмма",
	Column: "Колонка",
	Columns: "Колонки",
	"Color column": "Колонка цвета",
	Common: "Общие",
	"Copy of": "Копия от",
	Count: "Счёт",
	"Created on": "Созданно",
	Data: "Данные",
	"Data source": "Источник данных",
	Day: "День",
	Delete: "Удалить",
	"Delete report": "Удалить отчет",
	Description: "Описание",
	Query: "Фильтр",
	Edit: "Изменить",
	"Enter query name": "Введите имя запроса",
	Export: "Экспорт",
	"To Excel": "В Excel",
	"To CSV": "В CSV",
	Filter: "Фильтр",
	"Filtering query": "Фильтр-запрос",
	"Frozen columns above": "Замороженные столбцы выше",
	Function: "Функция",
	Group: "Группировка",
	"Group summaries": "Суммирование",
	"Join data": "Присоединить источник данных",
	Heatmap: "Тепловая карта",
	"Labels column": "Колонка названий",
	Max: "Макс",
	Min: "Мин",
	Month: "Месяц",
	New: "Новый",
	"Click 'New' button to add a new report":
		"Нажмите кнопку 'Новый' чтобы добавить отчет",
	"Select any report from the list": "Выберите любой отчет из списка",
	"No reports": "Нет отчетов",
	"No saved queries": "Нет сохраненных запросов",
	"Last modified": "Последнее обновление",
	"New column name": "Имя новой колонки",
	"New report": "Новый отчет",
	"Please delete the related query filter first":
		"Пожалуйста, удалите вначале зависимый фильтр-запрос",
	"Please delete the related group rule first":
		"Пожалуйста, удалите вначале зависимую группировку",
	Rename: "Переименовать",
	"Report name": "Название отчета",
	Reports: "Отчеты",
	Save: "Сохранить",
	"Save query": "Сохранить запрос",
	Sort: "Сортировка",
	"Specify columns to group by and output(s)":
		"Задайте колонки для группировки и итоговые колонки",
	"Specify columns to sort by": "Задайте колонки для сортировки",
	Sum: "Сумма",
	Table: "Таблица",
	Title: "Заголовок",
	"Type to search": "Поиск",
	View: "Вид",
	Year: "Год",
	//chart
	Axes: "Шкалы",
	"X Axis": "X шкала",
	"Y Axis": "Y шкала",
	columns: "колонок",
	rows: "рядов",
	"Data series": "Серии данных",
	"Chart type": "Тип чарта",
	"Keys column": "Колонка ключей",
	"X axis column": "Колонка X шкалы",
	"Values column": "Колонка чисел",
	Color: "Цвет",
	"Marker type": "Тип маркера",
	"Fill marker": "Маркер с заполнением",
	Legend: "Легенда",
	"Logarithmic scale": "Логарифмическая шкала",
	Gridlines: "Сетка",
	Bottom: "Внизу",
	None: "Без легенды",
	Right: "Справа",
	Line: "Линейный график",
	Spline: "Сглаженный график",
	Area: "С областями",
	"Stacked area": "С областями и накоплениями",
	"Spline area": "Сглаженный с областями",
	Bar: "Гистограмма",
	"Stacked bar": "Гистограмма с накоплениями",
	Radar: "Лепестковая",
	Pie: "Круговая",
	Donut: "Кольцевая",
	"Create copy": "Создать копию",
	circle: "круг",
	square: "квадрат",
	triangle: "треугольник",
	diamond: "ромб",
	"no markers": "без маркеров",
	"Vertical labels": "Вертикальные подписи",
	"Extract series from": "Извлечь серии из",
	True: "Истина",
	False: "Ложь",
	"Save filter to use it in other reports":
		"Сохраните фильтр, чтобы использовать его в других отчетах",
};