export default {
	actions: "Действия",
	back: "Назад",
	forward: "Вперёд",
	levelUp: "Вверх",
	name: "Имя",
	size: "Размер",
	type: "Тип",
	date: "Дата",
	copy: "Копировать",
	cut: "Вырезать",
	paste: "Вставить",
	upload: "Загрузить",
	remove: "Удалить",
	create: "Создать папку",
	rename: "Переименовать",
	location: "Местоположение",
	select: "Выбрать файлы",
	sizeLabels: ["Б","КБ","МБ","ГБ"],
	iconsView: "Вид: плитка",
	tableView: "Вид: таблица",
	hideTree: "Спрятать дерево",
	showTree: "Показать дерево",
	collapseTree: "Свернуть дерево",
	expandTree: "Развернуть дерево",
	saving: "Сохранение...",
	errorResponse: "Ошибка: изменения не сохранены!",
	replaceConfirmation: "Эта папка уже содержит файлы с таким именем. Заменить их ?",
	createConfirmation: "Папка с таким именем уже существует. Заменить её ?",
	renameConfirmation: "Файл с таким именем уже существует. Заменить его ?",
	yes: "Да",
	no: "Нет",
	types:{
		folder: "Папка",
		doc: "Текстовый документ",
		excel: "Excel",
		pdf: "PDF",
		pp: "PowerPoint",
		text: "Текстовый файл",
		video: "Видео",
		image: "Изображение",
		code: "Код",
		audio: "Аудио",
		archive: "Архив",
		file: "Файл"
	}
};