export default {
	//general
	Done: "Done",
	Table: "Table",
	Tree: "Tree",
	Chart: "Chart",
	"Click to configure": "Click to configure",
	"Configure Pivot": "Configure Pivot",
	Total: "Total",
	//settings
	Fields: "Fields",
	Methods: "Methods",
	Columns: "Columns",
	"Add column": "Add column",
	Rows: "Rows",
	"Add row": "Add row",
	"Clean rows": "Clean rows",
	"Values on the row axis": "Values on the row axis",
	Filters: "Filters",
	"Add filter": "Add filter",
	"Group By": "Group By",
	"Chart type": "Chart type",
	"Logarithmic scale": "Logarithmic scale",
	"X axis title": "X axis title",
	"Y axis title": "Y axis title",
	"Scale color": "Scale color",
	"Circled lines": "Circled lines",
	Horizontal: "Horizontal",
	Stacked: "Stacked",
	Lines: "Lines",
	"Y axis lines": "Y axis lines",
	"X axis lines": "X axis lines",
	Line: "Line",
	Radar: "Radar",
	Bar: "Bar",
	Area: "Area",
	Spline: "Spline",
	"Spline Area": "Spline Area",
	Pie: "Pie",
	Donut: "Donut",
	Scatter: "Scatter",
	Values: "Values",
	"Add value": "Add value",
	"Field not defined": "Field not defined",
	Highlight: "Highlight",
	"Min X": "Min X",
	"Max X": "Max X",
	"Min Y": "Min Y",
	"Max Y": "Max Y",
	Footer: "Footer",
	"Total Column": "Total Column",
	Off: "Off",
	On: "On",
	"Sum Only": "Sum Only",
	"3D": "3D",
	"Legend align": "Legend align",
	Labels: "Labels",
	Tooltips: "Tooltips",
	Markers: "Markers",
	Square: "Square",
	Triangle: "Triangle",
	Diamond: "Diamond",
	Round: "Round",
	Left: "Left",
	Center: "Center",
	Right: "Right",
	Top: "Top",
	Middle: "Middle",
	Bottom: "Bottom",
	"Fill area": "Fill area",
	//operations
	sum: "sum",
	min: "min",
	max: "max",
	count: "count",
	counta: "counta",
	countunique: "countunique",
	avg: "avg",
	wavg: "wavg",
	median: "median",
	product: "product",
	stdev: "stdev",
	stdevp: "stdevp",
	var: "var",
	varp: "varp",
	any: "any",
	complex: "complex",
	"Incorrect formula in values": "Incorrect formula in values",
};