export default {
	//general
	Done: "Fine",
	Table: "Tabella",
	Tree: "Albero",
	Chart: "Grafico",
	"Click to configure": "Cliccare su per configurare",
	"Configure Pivot": "Configurazione di Pivot",
	Total: "Totale",
	//settings
	Fields: "Campi",
	Methods: "Metodi",
	Columns: "Colonne",
	"Add column": "Aggiungi colonna",
	Rows: "Righe",
	"Add row": "Aggiungi riga",
	"Clean rows": "Righe pulite",
	Filters: "Filtri",
	"Add filter": "Aggiungi filtro",
	"Group By": "Raggruppa per",
	"Chart type": "Tipo di grafico",
	"Logarithmic scale": "Scala logaritmica",
	"X axis title": "Titolo dell'asse X",
	"Y axis title": "Titolo dell'asse Y",
	"Scale color": "Colore scala",
	"Circled lines": "Bordo circolare",
	Horizontal: "Orizzontale",
	Stacked: "Impilata",
	Lines: "Linee",
	Line: "A linee",
	Radar: "Radar",
	Bar: "A barre",
	Area: "Con aree",
	Spline: "Levigato",
	"Spline Area": "Levigato con aree",
	Pie: "Grafico a torta",
	Donut: "Grafico a ciambella",
	Values: "Valori",
	"Add value": "Aggiungi valore",
	"Field not defined": "Campo non definito",
	Highlight: "Evidenziare",
	"Min X": "Minimo X",
	"Max X": "Massimale X",
	"Min Y": "Minimo Y",
	"Max Y": "Massimale Y",
	Footer: "Piè di pagina",
	"Total Column": "Colonna totale",
	Off: "Spegnere",
	On: "Accendere",
	"Sum Only": "Solo somma",
	"3D": "3D",
	"Show values inside": "Mostra i valori all'interno",
	//operations
	count: "conti.num.",
	max: "max",
	min: "min",
	avg: "media",
	wavg: "med.pond.",
	any: "qualsiasi",
	sum: "somma",
	complex: "complesso",
	"Incorrect formula in values": "Formula errata nei valori",
};