export default {
	//general
	Done: "Готово",
	Table: "Таблица",
	Tree: "Дерево",
	Chart: "График",
	"Click to configure": "Нажмите, чтобы настроить",
	"Configure Pivot": "Конфигурация Pivot",
	Total: "Итого",
	//settings
	Fields: "Поля",
	Methods: "Методы",
	Columns: "Столбцы",
	"Add column": "Добавить столбец",
	Rows: "Ряды",
	"Add row": "Добавить ряд",
	"Clean rows": "Без повторений",
	Filters: "Фильтры",
	"Add filter": "Добавить фильтр",
	"Group By": "Сгруппировать по",
	"Chart type": "Тип графика",
	"Logarithmic scale": "Логарифмическая шкала",
	"X axis title": "Название оси X",
	"Y axis title": "Название оси Y",
	"Scale color": "Цвет оси",
	"Circled lines": "Круговая граница",
	Horizontal: "Горизонтальный",
	Stacked: "С накоплением",
	Lines: "Линии",
	Line: "Линейный",
	Radar: "Лепестковый",
	Bar: "Гистограмма",
	Area: "С областями",
	Spline: "Сглаженный",
	"Spline Area": "Сглаженный с областями",
	Values: "Значения",
	"Add value": "Добавить значение",
	"Field not defined": "Поле не определено",
	Highlight: "Подсветка",
	"Min X": "Мин. X",
	"Max X": "Макс. X",
	"Min Y": "Мин. Y",
	"Max Y": "Макс. Y",
	Footer: "Футер",
	"Total Column": "Итоговый столбец",
	Off: "выкл.",
	On: "вкл.",
	"Sum Only": "Только сумма",
	//operations
	count: "количество",
	max: "максимум",
	min: "минимум",
	avg: "среднее",
	wavg: "средневзвешенное",
	any: "любое",
	sum: "сумма",
	complex: "составная",
	"Incorrect formula in values": "Неверная формула в значениях",
};