export default {
	"Link arrow": "Link arrow",
	"Default link arrow": "Default link arrow",
	"Link mode": "Link mode",
	"Default link mode": "Default link mode",
	Fill: "Fill",
	Size: "Size",
	"Block settings": "Block settings",
	"Default block size": "Default block size",
	Font: "Font",
	"Line style": "Line style",
	"Border style": "Border style",
	Content: "Content",
	None: "None",
	Reset: "Reset",
	Autoplace: "Autoplace",
	Apply: "Apply",

	// Titles of default groups in the list of shapes
	Block: "Block",
	Flow: "Flow",
	Common: "Common",
	Extra: "Extra",

	// Built-in shapes: block
	Circle: "Circle",
	Dot: "Dot",
	Head: "Head",
	Heptagon: "Heptagon",
	Join: "Join",
	Junction: "Junction",
	Octagon: "Octagon",
	Pentagon: "Pentagon",
	Plus: "Plus",
	Rtriangle: "Right triangle",
	Star: "Star",
	Tail: "Tail",
	Trapezoid: "Trapezoid",
	Triangle: "Triangle",
	// Built-in shapes: flow
	Action: "Action",
	Collate: "Collate",
	Connector: "Connector",
	Data: "Data",
	Database: "Database",
	Decision: "Decision",
	Display: "Display",
	Document: "Document",
	Input: "Input",
	Internal: "Internal",
	Looplimit: "Loop limit",
	Multidoc: "Multiple documents",
	Note: "Note",
	Operation: "Operation",
	Or: "Or",
	Output: "Output",
	Preparation: "Preparation",
	Process: "Process",
	Sort: "Sort",
	Start: "Start",
	Storage: "Storage",
	Subroutine: "Subroutine",
	// Built-in shapes: common
	Default: "Default",
	Organization: "Organization",
	Text: "Text",
};
