export default {
	"Link arrow": "Стрелка линии",
	"Default link arrow": "Стрелка линии по умолчанию",
	"Link mode": "Тип линии",
	"Default link mode": "Тип линии по умолчанию",
	Fill: "Заливка",
	Size: "Размер",
	"Block settings": "Параметры блока",
	"Default block size": "Размер блока по умолчанию",
	Font: "Шрифт",
	"Line style": "Тип штриха",
	"Border style": "Тип границы",
	Content: "Текст",
	None: "Без стрелки",
	Reset: "Сброс",
	Autoplace: "Авторасстановка",
	Apply: "Применить",

	// Titles of default groups in the list of shapes
	Block: "Блок",
	Flow: "Блок-схема",
	Common: "Основные",
	Extra: "Дополнительные",

	// Built-in shapes: block
	Circle: "Круг",
	Dot: "Результат",
	Head: "Проблема",
	Heptagon: "Гептагон",
	Join: "Узел управления",
	Junction: "Сумматор",
	Octagon: "Октагон",
	Pentagon: "Пентагон",
	Plus: "Плюс",
	Rtriangle: "Прямоугольный треугольник",
	Star: "Звезда",
	Tail: "Вывод",
	Trapezoid: "Трапеция",
	Triangle: "Равнобедренный треугольник",
	// Built-in shapes: flow
	Action: "Терминатор",
	Collate: "Сопоставление",
	Connector: "Соединитель",
	Data: "Память с прямым доступом",
	Database: "База данных",
	Decision: "Решение",
	Display: "Отображение",
	Document: "Документ",
	Input: "Ручной ввод",
	Internal: "Внутренняя память",
	Looplimit: "Ручное ограничение",
	Multidoc: "Несколько документов",
	Note: "Заметка",
	Operation: "Ручная операция",
	Or: "ИЛИ",
	Output: "Выходные данные",
	Preparation: "Подготовка",
	Process: "Процесс",
	Sort: "Сортировка",
	Start: "Начало",
	Storage: "Сохранённые данные",
	Subroutine: "Типовой процесс",
	// Built-in shapes: common
	Default: "Блок по умолчанию",
	Organization: "Организация",
	Text: "Текст",
};
