export default {
	Undo: "Undo",
	Redo: "Redo",
	Print: "Print",
	"Full screen": "Full screen",
	Style: "Style",
	"Text style": "Text style",
	"Font family": "Font family",
	"Font size": "Font size",
	Bold: "Bold",
	Italic: "Italic",
	Underline: "Underline",
	Strikethrough: "Strikethrough",
	Superscript: "Superscript",
	Subscript: "Subscript",
	"Text color": "Text color",
	"Background color": "Background color",
	"Paint format": "Paint format",
	"Left align": "Left align",
	"Center align": "Center align",
	"Right align": "Right align",
	Justify: "Justify",
	"Line height": "Line height",
	Indent: "Indent",
	Outdent: "Outdent",
	"Insert link": "Insert link",
	"Insert image": "Insert image",
	"Bulleted list": "Bulleted list",
	"Numbered list": "Numbered list",
	"Clear formatting": "Clear formatting",
	File: "File",
	New: "New",
	Import: "Import",
	Export: "Export",
	PDF: "PDF",
	DOCX: "DOCX",
	"Print...": "Print...",
	Edit: "Edit",
	Cut: "Cut",
	Copy: "Copy",
	Paste: "Paste",
	View: "View",
	Fullscreen: "Fullscreen",
	"Layout mode": "Layout mode",
	"Classic mode": "Classic mode",
	"Document mode": "Document mode",
	Insert: "Insert",
	Link: "Link",
	Image: "Image",
	Format: "Format",
	Text: "Text",
	Paragraph: "Paragraph",
	Quote: "Quote",
	"Heading 1": "Heading 1",
	"Heading 2": "Heading 2",
	"Heading 3": "Heading 3",
	"Heading 4": "Heading 4",
	"Heading 5": "Heading 5",
	"Heading 6": "Heading 6",
	Default: "Default",
	Align: "Align",
	Left: "Left",
	Center: "Center",
	Right: "Right",
	Justified: "Justified",
	Lists: "Lists",
	Help: "Help",
	Hotkeys: "Hotkeys",
	"Edit image": "Edit image",
	"Delete image": "Delete image",
	"Image options": "Image options",
	Width: "Width",
	Height: "Height",
	"Lock aspect ratio": "Lock aspect ratio",
	Source: "Source",
	"Alternative description": "Alternative description",
	Alignment: "Alignment",
	"Select an image to see image options":
		"Select an image to see image options",
	"Edit link": "Edit link",
	"Copy link": "Copy link",
	Unlink: "Unlink",
	Apply: "Apply",
	Cancel: "Cancel",
	"Enter text to display": "Enter text to display",
	"Paste link": "Paste link",
	"Link copied to clipboard": "Link copied to clipboard",
	"The operation failed! Please check your browser's clipboard permissions.":
		"The operation failed! Please check your browser's clipboard permissions.",
	"Horizontal line": "Horizontal line",
	Search: "Search",
	"Smileys & People": "Smileys & People",
	"Animals & Nature": "Animals & Nature",
	Activity: "Activity",
	"Travel & Places": "Travel & Places",
	"Food & Drink": "Food & Drink",
	Objects: "Objects",
	"Search results": "Search results",
	Symbols: "Symbols",
	Basic: "Basic",
	Currency: "Currency",
	Quotations: "Quotations",
	Mathematical: "Mathematical",
	"Extended Latin": "Extended Latin",
	Arrows: "Arrows",
	Emoji: "Emoji",
	"Special characters": "Special characters",
	"Continuous painting": "Continuous painting",
	Document: "Document",
	"New line": "New line",
	Action: "Action",
	Hotkey: "Hotkey",
};