export default {
	Edit: "Править",
	Done: "Готово",
	"Delete task": "Удалить задачу",
	"Delete link": "Удалить связь",
	"The task will be deleted permanently, are you sure?":
		"Задача будет удалена навсегда, вы уверены?",
	"The link will be deleted permanently, are you sure?":
		"Связь будет удалена навсегда, вы уверены?",
	Predecessors: "Предшествующие",
	Successors: "Последующие",

	Title: "Название",
	"Start date": "Начало",
	"End date": "Конец",
	Duration: "Длительность",
	Progress: "Готовность",
	Notes: "Заметки",
	Type: "Тип",
	Project: "Проект",
	Milestone: "Веха",
	"Add task": "Добавить задачу",
	"Add project": "Добавить проект",
	"(no title)": "(без названия)",
	"Save changes?": "Сохранить изменения?",

	"Related tasks": "Связанные задачи",
	Task: "Задача",
	Link: "Связь",
	"End to start": "конец-начало",
	"Start to start": "начало-начало",
	"End to end": "конец-конец",
	"Start to end": "начало-конец",

	Lasts: "Длится",
	day: "день",
	days: "дней",

	"Add assignment": "Добавить",
	Assignment: "Назначение",
	Assignments: "Назначения",
	Assigned: "Назначены",
	"Delete assignment": "Удалить назначение",
	"Are you sure to delete this assignment?":
		"Вы действительно хотите удалить это назначение?",
	"No resources to add": "Нет ресурсов",
	Unassigned: "Без назначения",

	hour: "ч",
	"Hours per": "Часы в",
	"Tasks per": "Задачи в",
	Name: "Имя",
	Hours: "Часы",
	Tasks: "Задачи",
	month: "месяц",
	week: "неделю",
	quarter: "квартал",
	year: "год",

	"Split task": "Разделенная задача",
	"Planned dates": "Планируемые даты",
	"Planned dates will be removed, are you sure?":
		"Запланированные даты будут удалены, вы уверены?",
	"Add dates": "Запланировать даты",
	"Remove dates": "Удалить даты",
};