export default {
	Edit: "编辑",
	Done: "完成了",
	"Delete task": "删除任务",
	"Delete link": "删除链接",
	"The task will be deleted permanently, are you sure?":
		"该任务将被永久删除, 您确定?",
	"The link will be deleted permanently, are you sure?":
		"该链接将被永久删除, 您确定?",
	Predecessors: "前辈",
	Successors: "后继者",

	Title: "标题",
	"Start date": "开始日期",
	"End date": "结束日期",
	Duration: "持续时间",
	Progress: "进展",
	Notes: "笔记",
	Type: "类型",
	Project: "项目",
	Milestone: "里程碑",
	"Add task": "添加任务",
	"Add project": "添加项目",
	"(no title)": "(无题)",
	"Save changes?": "保存更改?",

	"Related tasks": "相关任务",
	Task: "任务",
	Link: "链接",
	"End to start": "结束开始",
	"Start to start": "开始开始",
	"End to end": "端到端",
	"Start to end": "开始到结束",

	Lasts: "持续",
	day: "天",
	days: "天",

	"Add assignment": "添加作业",
	Assignments: "作业",
	Assigned: "已分配",
	"Delete assignment": "删除作业",
	"Are you sure to delete this assignment?": "您确定要删除此作业吗?",
	"No resources to add": "没有资源",
	Unassigned: "未分配",

	hour: "小时",
	"Hours per day": "每天营业时间",
	"Tasks per day": "每天的任务",
	Name: "姓名",
	Hours: "小时",
	Tasks: "任务",
};