export default {	
	apply: "Применить",
	bar: "Столбчатая",
	cancel: "Отмена",
	chart: "Диаграмма",
	chartType: "Тип диаграммы",
	columns: "Колонки",
	count: "количество",
	date: "дата",
	datepicker: "дата",
	fields: "Поля",
	filters: "Фильтры",
	groupBy: "Группировать по полю",
	line: "Линейная",
	logScale: "Логарифмическая шкала",
	max: "макс",
	min: "мин",
	multicombo: "мульти-список",
	operationNotDefined: "Операция не задана",
	layoutIncorrect: "pivotLayout должен быть задан как Array",
	pivotMessage: "Конфигурация Пивота",
	popupHeader: "Настройки Пивота",
	radar: "Паутина",
	radarArea: "Паутина с фоном",
	rows: "Строки",
	select: "список",
	settings: "Настройки",
	stackedBar: "Гистограмма с накоплением",
	sum: "сумма",
	text: "текст",
	total: "Всего",
	values: "Поля",
	valuesNotDefined: "Поля или группировка не заданы",
	windowTitle: "Настройки Пивота",
	windowMessage: "перетащите поле сюда"
};