export default {  
		apply: "Utför"
		bar: "Bar"
		cancel: "Stäng"
		chart: "Chart"
		chartType: "Chart type"
		columns: "Kolumner"
		count: "Count"
		date: "Date"
		datepicker: "Datepicker"
		fields: "Fält"
		filters: "Filter"
		groupBy: "Group by"
		layoutIncorrect: "pivotLayout should be an Array instance"
		line: "Line"
		logScale: "Logarithmic scale"
		max: "Max"
		min: "Min"
		multicombo: "Multi-select"
		operationNotDefined: "Operation not defined"
		pivotMessage: "Urval"
		popupHeader: "Pivot Settings"
		radar: "Radar"
		radarArea: "Area Radar"
		richselect: "richselect"
		rows: "rader"
		select: "Select"
		settings: "settings"
		stackedBar: "Stacked Bar"
		sum: "Sum"
		text: "Text"
		total: "Totalt antal"
		values: "Värden"
		valuesNotDefined: "Värden eller gruppfältet är inte definierade"
		windowMessage: "Flytta fält hit"
		windowTitle: "Klicka för att konfigurera"
}
